interlay/interbtc-ui

src/components/UI/InterlayRouterLink/index.tsx, src/pages/Dashboard/Stats/index.tsx
In the process of transaction non-blocking feature, I found this bug and quickly fixed it.
=> fix: correct underline effect of InterlayRouterLink

package.json
The production build for the application was failing due to a BigInt to number conversion issue. This issue is listed here: https://polkadot.js.org/docs/usage/FAQ/#under-my-babel-build-i-have-a-bigint-to-number-conversion-error and was fixed with the approach here: https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299
=> fix: resolve bigint dependency error in production build

src/App.tsx, src/common/actions/general.actions.ts, src/common/reducers/general.reducer.ts, src/common/types/actions.types.ts, src/common/types/util.types.ts, src/parts/Topbar/index.tsx
Hi @nud3l @savudani8 - scope of this ticket is to add support for the governance token to the relay chain and general state, rather than add it to the features (e.g. currency selector dropdown, and transfer feature). Once this is done, the changes to support at the feature level can be made separately as they'll be quite small.
My biggest concern here is that I've overlooked something. I've been through the code and referenced instances of collateral token, but could you take a look and let me know if this looks right to you?
I could also do with some help testing - I'm not sure how to create an account with governance tokens, so I'm not able to check that the balance is correct.
=> feature: add governance token to relay chain and general state

src/components/NumberInput/NumberInput.stories.tsx, src/components/NumberInput/index.tsx, src/pages/Bridge/WrappedTokenField/index.tsx
~~@crypto-engineer any thoughts on this? I'm not entirely happy with attaching event listeners in this way, but I can't use createRef (which is how I'd usually handle this) or onWheel (see comments in code).~~
Ignore this :) as soon as I'd opened this PR I realised I could attach the ref to the parent element.
=> [feature]: Prevent increment/decrement on scroll

src/App.tsx, src/parts/Sidebar/SidebarContent/Navigation/index.tsx
This PR:
1. Adds disabled items to the navigation
* All features are now in the nav, including vaults and staking. @nud3l let me know if any of these should be suppressed altogether.
2. Disables routes for all features other than transfer
3. Redirects from the home page to the transfer feature.
Note: I wouldn't usually leave commented out code in the codebase, but in this case I I think it make sense given that the routes are going to be reactivated by reverting the code changes exactly. 
Test scenarios:
* Loading the app now redirects to the transfer page
* Hitting disabled feature urls directly returns a 404:
* '/bridge',
* '/transfer',
* '/transactions',
* '/staking',
* '/dashboard',
* '/dashboard/vaults',
* '/dashboard/parachain',
* '/dashboard/oracles',
* '/dashboard/issue-requests', …
=> feature: disabled link component

package.json, src/common/utils/utils.ts, src/pages/Bridge/RedeemForm/index.tsx
Redeems were failing because the change in the type of vault IDs from `AccountId` to `InterbtcPrimitivesVaultId` hadn't been made in this repo
=> fix: Use full InterbtcPrimitivesVaultId object

.env.kintsugi, src/App.tsx, src/assets/locales/en/translation.json, src/constants.ts, src/pages/Transfer/TransferForm/index.tsx, src/parts/AccountModal/index.tsx, src/parts/Topbar/index.tsx
This PR adds all the functions to enable transfer on Kintsugi. Successfully tested the current code to transfer KSM and KINT. Successful transactions can be seen here: https://kintsugi.subscan.io/account/5FkGaH4iuUTZaW8PwDM62xN7eZeiaVLBQV4z8Yp6p33jbp5o?tab=transfer
- Hotfix to use the correct ss58 prefix. I've left a comment in the code since I've just implemented using a constant. Instead, this should be fetched at runtime. We can do that in a later sprint. As a related comment, @savudani8 is it possible to pass through all the RPC calls, queries, and extrinsics from the parachain instead of redefining them in our lib. For example, I'd like to call `api.rpc.properties()` which is not defined on interbtc-api but we could pass through from the underlying chain since it's implemented by …
=> activate transfer of KSM, KINT, KBTC on kintsugi

src/assets/locales/en/translation.json, src/parts/Sidebar/SidebarContent/Navigation/index.tsx
Note: can't be merged into master as that branch doesn't have the disabled navigation commit. PR goes into kintsugi branch.
Adds coming soon to the nav items as per Jay's design. @nud3l after making the changes I saw your comment in Discord. PR's in draft, so here if we want it but can be discarded if not.
=> feature: add coming soon to disabled links

package.json, src/pages/Vault/UpdateCollateralModal/index.tsx, src/pages/Vault/index.tsx, yarn.lock
Vault collateralisation is working now - users can deposit and withdraw. This has been tested against an account with lockedBTC, and an account with no lockedBTC.
This PR blocks the API call if a user has no lockedBTC. Hitting the API in that case will cause an error to be returned (correctly - the calculation won't work against a value of zero) so it makes sense to set collateralisation to ∞ in the client as this will always be the correct value for an account with no locked BTC.
This is a quick fix to get the release out - we should rethink the logic when implementing the updated vault dashboard. The original logic assumed that `undefined` was not a valid value for collateralisation. This PR patches that, but ideally we need to refactor properly on the assumption that undefined is …
=> fix: getVaultCollateralization

src/parts/Sidebar/SidebarContent/Navigation/index.tsx
Hide the T&C link if the link has been set to an empty string (this will suppress it for the testnet release)
=> fix: suppress T&Cs link if returned as empty string

src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/RedeemedChart/index.tsx
=> fix: correct colors in RedeemedChart

.env.testnet, craco.config.js, package.json, yarn.lock
- Updates polkadot-js to 7.7.x
- Updates interbtc-js to 1.6.0
- Resolves bn.js to fix a type error with polkadot.js during runtime as reported here https://github.com/polkadot-js/api/issues/4024
- Resolves react-error-overlay to fix "Uncaught ReferenceError: process is not defined" during hot-reloading as reported here https://github.com/facebook/create-react-app/issues/11771.
- Project compiles with `yarn build` and `yarn start`
I've manually tested issue and redeem and clicked through all dashboards.
=> refactor: upgrade polkadot.js and interbtc-js dependencies

src/pages/Bridge/IssueForm/index.tsx, src/pages/Bridge/RedeemForm/index.tsx
This is a workaround for the issue of stale vault data on submit. This could definitely be improved by refactoring how we fetch data, but this is intended to be a quick fix so I've kept the changes to a minimum to reduce testing overhead and avoid the risk of regressions.
This PR makes the following changes to the issue request:
1. Removes the request for vaults on initial render.
2. Remove the vault capacity check from the onChange field validation.
3. Requests the vaults and validates capacity on submit so that the data is always fresh.
4. If there is no vault with capacity, the error is appended to the form field (as happens now)
* If this happens the form submission is cancelled.
5. If there is a vault with capacity, the form is submitted. 
In UI terms there are no visual changes. …
=> fix: validate vaults before issuing

src/pages/Transactions/IssueRequestsTable/IssueRequestModal/IssueRequestStatusUI/ConfirmedIssueRequest/index.tsx
There was a type error such that users would always get an error when trying to manually execute.
Confirmed with a user on testnet that the fix is working:
=> fix: manual issue execution

src/pages/Bridge/RedeemForm/index.tsx
I think this works as a quick fix - anything better would need quite a bit of refactoring. Solution here is different from the issue form:
1. We are already calling `getVaultsWithRedeemableTokens()` on submit when the relevant condition is met, so this value will always be up to date.
2. Premium redeem vaults were being fetched on initial render. I've kept the api call as it's required to control layout, but only stored a boolean value in state as we need to refetch the premium redeem vaults on submission so would never use the value itself.
3. Premium redeem vaults are called again on submit, and this is the value that is used to handle the transaction.
This hasn't really been tested with premium redeem vaults as a value isn't being returned locally. Will start a discussion in Discord …
=> refetch premium redeem vaults on submission

src/pages/Transfer/CrossChainTransferForm/index.tsx, src/utils/relay-chain-api/create-relay-chain-api.ts, src/utils/relay-chain-api/get-relay-chain-balance.ts, src/utils/relay-chain-api/index.tsx, src/utils/relay-chain-api/transfer-to-parachain.ts, src/utils/relay-chain-api/transfer.ts, src/utils/relay-chain-api/types.ts
This PR does three things: 
1. Extends the relay chain api utilities to fetch the collateral token balance
2. Displays the available amount on the XCM transfer form
3. Validates the amount so that a user can't send a transaction for greater than the balance.
This resolves the issue where a user could send a transaction for greater than the amount they hold, causing them to lose their transaction fee.
All code relating the relay chain api (including types) is being kept together. This was implemented quite quickly, and we'll be reviewing how its been implemented before doing any more work to support cross-chain transfer.
=> Fetch relay chain balance and validate on submit

src/common/actions/general.actions.ts, src/common/types/actions.types.ts, src/common/types/util.types.ts, src/config/relay-chains.tsx, src/pages/Staking/index.tsx, src/pages/Vault/index.tsx
- Simplify with:
```
type GovernanceTokenMonetaryAmount = MonetaryAmount<GovernanceToken, GovernanceUnit>;
type VoteGovernanceTokenMonetaryAmount = MonetaryAmount<VoteGovernanceToken, VoteUnit>;
```
(In the process of creating utility functions to handle user action specifically, I had to use the above types many times and found that they were repeated so simplified like so. It was quite straightforward so I made that change. @tomjeatt I'm sorry for that. It was made before we had discussed about refactoring approaches on the other PR. It's so straightforward that I have a lot of confidence.)
- It behaves like so:
1. Adding stake but not lock time: ‘Add more stake’.
2. Increasing lock time but not adding more stake: ‘Extend lock time’.
3. Adding stake and increasing lock time: ‘Add more …
=> feat: submit button text depending on user action in staking

src/assets/locales/en/translation.json, src/pages/Transactions/IssueRequestsTable/IssueRequestModal/index.tsx
This PR updates the modal styling to make the difference between amount/received much clearer.
=> refactor: issue modal styling

src/assets/locales/en/translation.json, src/pages/Bridge/IssueForm/index.tsx
This PR removes the limitation of 1 BTC on the testnet.
=> feat: remove MAXIMUM_ISSUABLE_WRAPPED_TOKEN_AMOUNT

src/pages/Bridge/IssueForm/index.tsx
This is a temporary fix for a bug with vault selection which seems to be occurring in the UI. This PR calls the vaults and selects a random vault in the UI. This should be happening in the lib (and was working before) so we should plan to revert this PR completely when we have a fix on the lib side.
=> fix: handle selecting vault in the UI

src/pages/Dashboard/IssuedChart/index.tsx, src/pages/Dashboard/cards/ActiveVaultsCard/index.tsx, src/pages/Dashboard/cards/CollateralLockedCard/index.tsx, src/pages/Dashboard/sub-pages/Home/ActiveCollatorsCard/index.tsx, src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/RedeemedChart/index.tsx
- on issue/TVL, registered vaults, and redeems graph, move the date 1 day back because the graph counts "value before the end of the given day" but it's more natural to display "value ON the given day (i.e. after the start of the given day".
- on collators, it was completely wrong, so switched to using the same logic as all the other graphs to get correct timestamps.
=> fix: all date axes on graphs in the dashboard

src/components/CopyAddressButton/index.tsx, src/parts/AccountModal/index.tsx
This PR adds a copy icon to the account selector so users can select an address. On click, the icon switches to a tick and is then reset after 1 second.
fixes #225
=> Copy address from account modal

src/pages/Dashboard/cards/CollateralizationCard/index.tsx
change it to use lib function that sums capacities of each vault, rather than using total system collateralisation (which fails if there are some vaults below the safe collateral threshold, but others are above it)
=> fix: switch dashboard capacity card 

src/pages/Transactions/IssueRequestsTable/IssueRequestModal/BTCPaymentPendingStatusUI/index.tsx
~~Increasing the size to 256px with a margin around the code (this is critical to work with Bitcoin.com wallet and probably some other too).~~
Adding margin around the Bitcoin QR code. The problem was lack of white margin around the QR code square. With the margin added, the code gets read instantly. Tested with 3 different wallets and QR code reader.
=> fix: added margin around btc qr code

src/utils/relay-chain-api/constants.ts
The fees for the relay chain have been modified, see https://github.com/paritytech/polkadot/pull/5202/files.
The weight of the message we are trying to send = `weight = 4_000_000_000`
For Kusama:
ExtrinsicBaseWeight = 80_350 * WEIGHT_PER_NANOS = 80_350_000
PricePerBaseWeight = 1/10 cent = 10^12 / 30_000 / 10
fee = (weight/ExtrinsicBaseWeight) * PricePerBaseWeight = (4_000_000_000 / 80_350_000) * (10^12 / 300_00 / 10)
= 165940676.208 (theoretical)
.. But due to rounding is actually 165940672
For polkadot:
ExtrinsicBaseWeight = 82_855 * WEIGHT_PER_NANOS = 82_855_000
PricePerBaseWeight = 1/10 cent = 10^10 / 100 / 10
(weight/ExtrinsicBaseWeight) * PricePerBaseWeight = (4_000_000_000 / 82_855_000) * (10^10 / 100 / 10)
= 482771106.149
For rococo:
ExtrinsicBaseWeight = 3_098_278 * …
=> fix: relay fees

src/config/relay-chains.tsx, src/parts/Sidebar/SidebarContent/index.tsx
Fixing switched logos of Wrapped and Governance token.
=> fix: show correct tokens logos

src/App.tsx, src/common/live-data/totals-watcher.ts, src/common/reducers/general.reducer.ts, src/common/reducers/vault.reducer.ts, src/components/Tokens/index.tsx, src/config/relay-chains.tsx, src/pages/Bridge/BurnForm/index.tsx, src/pages/Bridge/RedeemForm/index.tsx, src/pages/Bridge/index.tsx, src/pages/Dashboard/cards/CollateralLockedCard/index.tsx, src/pages/Dashboard/cards/CollateralizationCard/index.tsx, src/pages/Dashboard/cards/OracleStatusCard/index.tsx, src/pages/Dashboard/sub-pages/Oracles/OraclesTable/index.tsx, src/pages/Dashboard/sub-pages/Vaults/VaultsTable/index.tsx, src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/ReimbursedRedeemRequest/index.tsx, src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/RetriedRedeemRequest/index.tsx, src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/ReimburseStatusUI/index.tsx, src/pages/Transfer/CrossChainTransferForm/index.tsx, src/pages/Vaults/Vault/VaultStatusStatPanel/index.tsx, src/services/fetchers/issue-request-fetcher.ts, src/services/fetchers/redeem-request-fetcher.ts, src/utils/constants/currency.ts, src/utils/relay-chain-api/get-relay-chain-balance.ts, src/utils/relay-chain-api/transfer-to-relay-chain.ts
I found that we were referring to a relay chain's native tokens like DOT or KSM as collateral token. I think it's not correct. In the past, the relay chain's native token was the only collateral but now we are supporting multi-collaterals including KINT and USDC and more will be added. So I think we should update names accordingly.
This PR does not include any logical changes but just renaming. So I'd say it's safe to merge this PR without having a look at every single line of change in detail.
=> refactor: update collateral token to relay chain native token

src/pages/Dashboard/sub-pages/Home/LockedCollateralsCard/index.tsx
Fixing Locked Collateral Card component to work on Interlay. The governance token data will be used only when the price is available.
before
after
=> fix: locked collateral card handles undefined price of governance token

src/components/RedeemUI/ReimburseStatusUI/index.tsx
Simple PR to notify user about errors that happened during redeem reimbursement. (https://www.notion.so/interlay/Kintsugi-UI-prematurely-allows-redeem-cancellation-23106eed3a824158b14af41e81c59f9a)
=> feat: notify about error occuring during redeem reimbursement

src/componentLibrary/CTA/CTA.style.tsx, src/componentLibrary/CTA/CTA.tsx, src/componentLibrary/CTA/CTALink.tsx
This fixes a React error by using transient props to avoid custom props being passed down to the dom element
=> fix: use transient props to resolve react error

src/App.tsx
In current implementation, we are creating a query subscriptions in the effect hook of the App component to listen for balance changes. Subscription callback functions are depending on the global redux state which they also modify. Therefore a callback has to be modified when the balance state changes. However, we are not able to modify the callback of existing subscriptions and can only create new query subscription with different callback because of the limitations imposed by the polkadot.js api package. 
The problem of current implementation is that we are creating new subscription with modified callback with each state change, but are not closing the previous subscriptions. As a result, ever-increasing amount of subscriptions is created with each run of the effect hook which ends up …
=> fix: fixed subscriptions for token balances

src/components/AvailableBalanceUI/index.tsx, src/pages/Staking/index.tsx, src/pages/Transfer/CrossChainTransferForm/index.tsx, src/pages/Transfer/TransferForm/index.tsx, src/pages/Vaults/Vault/RequestIssueModal/index.tsx
https://www.loom.com/share/e0857334ac7d4f5389ede13b18231c9a
=> feat: add max balance buttons

src/pages/Bridge/RedeemForm/index.tsx
This PR solves this [ticket](https://www.notion.so/interlay/Sim-o-0a0076c888bc49d7a980bf372acf0aef?p=4080fb4cfc264c21a135d5e7f6b3315b).
The problem was that the `validateForm` function is called `onChange` of the Input. The `redeemFee` calculation needs the current input value, meaning that it has a direct dependency to it. When calling `validateForm`, this function was using the most recent input value, while the `redeemFee` was still using the previous input value. Thus, creating a state sync issue. The quickest and simpler solution  was bring the calculation inside `validateForm` in order to use the most recent input value instead.
Here is a [video](https://www.loom.com/share/83220d693e974559adabd846a50b795b) of the end result.
=> fix(bridge): redeem error mismatch

package.json, src/pages/Bridge/BurnForm/index.tsx, src/pages/Bridge/IssueForm/index.tsx, src/pages/Bridge/RedeemForm/index.tsx, src/pages/Staking/index.tsx, src/pages/Transfer/CrossChainTransferForm/index.tsx, src/pages/Transfer/TransferForm/index.tsx, src/pages/Vaults/Vault/RequestIssueModal/index.tsx, src/pages/Vaults/Vault/RequestRedeemModal/index.tsx, src/pages/Vaults/Vault/RequestReplacementModal/index.tsx, src/pages/Vaults/Vault/UpdateCollateralModal/index.tsx, yarn.lock
This PR upgrades react hook form to version 7, which included some breaking changes. There were some issues using the resolver (required for schema validation) with version 6, so better to bump the dependencies now.
=> chore: bump react-hook-form and resolve breaking changes

src/component-library/VaultCard/VaultCard.stories.tsx, src/component-library/VaultCard/VaultCard.style.tsx, src/component-library/VaultCard/VaultCard.tsx, src/component-library/theme/theme.base.css, src/component-library/theme/theme.ts, src/pages/Vaults/index.tsx
This makes the collateral score red for at risk vaults, as in the original design. Jay is working on a more accessible solution, but this is a quick change to bring the implementation into line with the original designs. Current implementation of the dashboard flags that a vault is at risk in the info box, but doesn't indicate which one.
=> refactor: colour variant for at risk vaults

.github/workflows/chromatic.yml
Update the workflow to specify a node version. This fixes the build issue with Chromatic.
=> fix: add specific node version to Chromatic workflow

src/component-library/Text/Dl/Dl.stories.tsx, src/component-library/Text/Dl/Dl.style.tsx, src/component-library/Text/Dl/Dl.tsx, src/component-library/Text/Dl/index.tsx, src/component-library/Text/index.tsx, src/component-library/index.tsx
Add a definition list component. This is a text component which is needed for the updated vault dashboard header. This is the only use case at the moment, so there are no variants but it can be extended as and when necessary.
=> feature: Dl component

src/assets/locales/en/translation.json, src/pages/Bridge/IssueForm/index.tsx, src/pages/Bridge/RedeemForm/index.tsx, src/pages/Vaults/Vault/RequestIssueModal/index.tsx
Handling the oracle being offline. Instead of throwing an error on rejection, informative error message is displayed under the BTC and wrapped BTC amount input element in the Issue and Redeem pages, respectively.
=> fix: handle offline oracle for issue and redeem

src/config/vaults.ts, src/pages/Dashboard/sub-pages/Vaults/VaultsTable/index.tsx, src/pages/Dashboard/sub-pages/Vaults/index.tsx, src/utils/hooks/api/use-get-collateral-thresholds.tsx
Fix to get threshold limits only for supported collateral threshold currencies in the VaultTable.
=> fix: get thresholds for supported collaterals only

src/components/IssueUI/IssueRequestStatusUI/CompletedIssueRequest/index.tsx, src/components/IssueUI/index.tsx, src/components/RedeemUI/RedeemRequestStatusUI/CompletedRedeemRequest/index.tsx, src/components/RedeemUI/index.tsx, src/pages/Dashboard/sub-pages/IssueRequests/IssueRequestsTable/index.tsx, src/pages/Dashboard/sub-pages/RedeemRequests/RedeemRequestsTable/index.tsx, src/pages/Vaults/Vault/VaultIssueRequestsTable/index.tsx, src/pages/Vaults/Vault/VaultRedeemRequestsTable/index.tsx
Changing the displayed block numbers from active block numbers to absolute parachain block numbers.
Diff: **Creation Block** and **Last Update Block** columns
Before
After
=> refactor: change displayed active block numbers to absolute parachain block numbers

src/pages/Bridge/IssueForm/index.tsx
- removed loading step. This step was keeping the `Issue` stuck on Loading.
- `Connect wallet` no more is disabled while wallet in not connected
=> fix(Bridge): Issue tab stuck on loading

src/component-library/Modal/Modal.style.tsx, src/component-library/Modal/Modal.tsx, src/component-library/theme/theme.ts
- close button miss aria-label and small size (hard to click on mobile)
- modal content wrapper `role` missing
- standardise modal padding according to Jay designs
- add missing overlay
In the future we need to improve styles and maybe implement `react-aria` and `react-stately` because there are some missing features
=> fix(Modal): styles and accessibility

package.json, src/pages/Vaults/Vault/index.tsx, yarn.lock
Hotfix vault thresholds - this is for the legacy dashboard so won't be supported when that is retired in the next few weeks, which is why I've not added the labels to the translation file.
=> hotfix: add thresholds

src/pages/Dashboard/sub-pages/IssueRequests/IssueRequestsTable/index.tsx, src/pages/Dashboard/sub-pages/RedeemRequests/RedeemRequestsTable/index.tsx
- full vault accountid
- user parachain address on redeem
- BTC tx details for redeem
Just uses full-sized string display for now. In the future could/should be replaced with a copy button or block explorer link
=> feat: add extra details to public issue+redeem dashboards

src/pages/Dashboard/cards/OracleStatusCard/index.tsx
This fixes the oracle exchange rate in master. Note: this may cause merge conflicts in the next release because the hotfix for kintsugi/interlay doesn't include the formatting utilities (which aren't in prod yet). If there are any any conflicts, accept changes from master.
=> Bug: Oracle exchange rate

src/pages/Vaults/Vault/components/TransactionHistory/TransactionHistory.styles.tsx, src/pages/Vaults/Vault/components/TransactionHistory/TransactionHistory.tsx, src/pages/Vaults/Vault/components/TransactionHistory/TransactionStatusTag.tsx, src/pages/Vaults/Vault/components/TransactionHistory/TransactionTable.tsx, src/utils/hooks/api/vaults/use-get-vault-transactions.tsx
This uses the modals from the transactions table to show issue and redeem request details. This is a quick fix to get the release out; we'll review the use of the modal, and if we decide to continue with it (rather than replace it) then we will need to refactor it, and move the modal components to a shared directory.
For now though, this is an acceptable solution - we'll be reviewing the dashboard and overview implementation soon, and we can review the modal at the same time.
=> Vault dashboard issue requests modal

src/utils/hooks/api/vaults/get-vault-data.ts
Fixing incorrect squid queries (wrong address format) that resulted in incorrect count of pending requests in Vault Overview page.
=> fix: ss58format accountId in queries

src/pages/Vaults/Vault/ReplaceTable/index.tsx, src/pages/Vaults/Vault/VaultDashboard.tsx, src/pages/Vaults/Vault/VaultIssueRequestsTable/index.tsx, src/pages/Vaults/Vault/VaultRedeemRequestsTable/index.tsx
This reverts the transaction tables on the vault dashboard. No need to review the tables themselves - these are exactly as they were before. Only changes that need to be looked at are to the VaultDashboard component.
=> feature: revert to previous versions of vault transaction tables

.github/workflows/chromatic.yml
Updating chromatic checkout action to version 2 in order to fix deployments that are not taking into account latest changes.
=> chore: update chromatic checkout action to v2

src/component-library/NumberInput/NumberInput.tsx, src/component-library/TokenInput/TokenInput.tsx
- Fixed balance rendering 0
- Stoped the component from emitting `onChange` on invalid input using a `RegEx`. This invalid input was being fixed by react-aria but we were still emitting `onChange`.
=> fix(TokenInput): balance and handle invalid input

src/utils/hooks/api/vaults/use-get-available-vaults.tsx
Fixing fetching of minimum collateral amount in vault onboarding to use correct amount for each collateral currency respectively.
=> fix(vault onboarding): get minimum collateral amount for used collateral currency

src/assets/locales/en/translation.json, src/components/RedeemUI/RedeemRequestStatusUI/PendingWithBtcTxNotFoundRedeemRequest/index.tsx
The `nav_vaults` key was being incorrectly used in place of the word 'Vault' in the redeem UI. This corrects that.
=> fix: remove incorrect usage of vaults nav item

src/component-library/Switch/Switch.tsx, src/component-library/Table/TableRow.tsx, src/component-library/theme/theme.ts
- `TableRow` changes allows interacting with html element such as `input` without emitting a `onRowAction` event.
- `Switch` changes adds emitting `onClick` and `onKeyDown` event under a single event called `onPress`.
- Theme changes are related to some colors needed for interlend
=> feat: changes to TableRow, Switch and theme

src/components/UI/InterlayModal/index.tsx
Fix scrolling opaque background issue when account selector height is greater than window height
=> fix: move opaque bg styles to parent element

package.json, src/pages/Loans/LoansOverview/LoansOverview.tsx, src/pages/Loans/LoansOverview/components/LoansInsights/LoansInsights.tsx, src/utils/constants/api.ts, src/utils/hooks/api/loans/use-get-account-loans-overview.tsx, src/utils/hooks/api/loans/use-get-account-positions.tsx, src/utils/hooks/api/loans/use-get-account-subsidy-rewards.tsx, src/utils/hooks/api/loans/use-get-loan-assets.tsx, src/utils/hooks/api/loans/use-get-loans-data.tsx, src/utils/hooks/api/loans/utils.ts, yarn.lock
- Upgrading lib version to 0.31.0, that changes how earned subsidy reward is returned. 
- Renaming `earnedReward` -> `subsidyReward` to make clear distinction between subsidies and interest rewards.
- Adding refetch interval to separate constant
- Creating one main function for refetching of positions, loan assets and rewards in `useGetAccountLoansOverview`, to refresh to be able to refresh all data with 1 call.
=> chore(interlend): update lib to 0.31.0, refactor subsidy rewards

src/components/IssueUI/IssueRequestStatusUI/ManualIssueExecutionUI/index.tsx
This PR contains a critical bug: https://github.com/interlay/interbtc-ui/pull/613/files. When an issue request is `PendingWithEnoughConfirmations` then the user can execute the issue request at any point in time without validation if the vault has any extra capacity: https://github.com/interlay/interbtc-ui/pull/613/files#r1027698085
=> fix: allow issue exeuction for confirmed issue requests

src/component-library/Alert/Alert.stories.tsx, src/component-library/Alert/Alert.style.tsx, src/component-library/Alert/Alert.tsx, src/component-library/Alert/index.tsx, src/component-library/index.tsx, src/pages/Loans/LoansOverview/components/BorrowLimit/BorrowLimit.style.tsx, src/pages/Loans/LoansOverview/components/BorrowLimit/BorrowLimit.tsx, src/pages/Loans/LoansOverview/components/CollateralModal/CollateralModal.tsx, src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx
Adding alert component to let user know when borrowing liquidity is lower than his borrow limit.
**Test**
- alert MUST be shown when liquidity is lower than user's borrow limit in Borrow section of LoanForm
- alert MUST NOT be shown otherwise  or in any other place
=> feat(loans): show alert when borrowing liquidity is low

src/component-library/Meter/use-meter.tsx
Return 100 as max range when no ranges is provided
There is no max range if ranges is provided
Max range defaults to 100
Same as https://github.com/interlay/interbtc-ui/pull/707
=> fix(Meter): handle use-meter missing ranges

src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx
On loan forms, focusing the input and blur it, makes the button loses disable.
Button loses disable by focus and unfocusing the input.
Button is disabled until valid input.
- lend asset on lending page
=> fix(Loans): loan form disable btn

src/pages/Loans/LoansOverview/hooks/use-loan-form-data.tsx, src/pages/Vaults/VaultsOverview/utils/use-deposit-collateral.tsx, src/utils/hooks/api/tokens/use-get-balances.tsx
Added some functionally primarily to handle available balance for governance.
There was no reusable implementation to deduct governance fees from transaction that involves governance tokens. Such as lending Governance or using it as collateral for a vault.
Add getter of balance that includes logic for when we are trying to get governance available balance.
Check if necessary for fees is deducted from the following flows:
- Vault Onboarding with governance token as collateral.
- Lending with governance token.
=> refactor: add useGetBalances helpers

src/pages/Vaults/Vault/RequestReplacementModal/index.tsx
Addresses #745 
Replace request transactions validation used to not check for:
- Griefing collateral
- Amounts below dust value
Dust value was checked on submit
Replace request transactions validation checks now:
- Requests cannot be made below BTC dust value
- Verifies and displays the griefing collateral amount
- Make sure to have access to a vault with at least some iBTC/kBTC locked
- Go to the vault dashboard and replace vault
- Opens the replace modal
- Try to enter a replace amount with insufficient governance balance -> validation error
- Try to enter a replace amount below BTC dust value -> validation error
=> fix: add check for required griefing collateral

src/component-library/Meter/Meter.stories.tsx, src/component-library/Meter/Meter.style.tsx, src/component-library/Meter/Meter.tsx, src/component-library/Meter/RangeIndicators.tsx
Fixes https://github.com/interlay/interbtc-ui/issues/761
Indicators overlap
Indicators do not overlap.
- On lending page, try combining assets as collateral with small thresholds ranges.
=> fix(Meter): overlapping indicators

package.json, src/component-library/CTA/BaseCTA.tsx, src/component-library/CTA/CTA.style.tsx, src/component-library/CTA/CTA.tsx, yarn.lock
When using a button, it is not a good practise to solely pass `onClick` prop because this event does not consider `Enter` key from using the keyboard.
React-aria handles this with `useButton` by exposing an event called `onPress`, which will be emitted with `Mouse` and `Keyboard`.
There should be no breaking changes.
**NOTE:** I had to add `useFocusVisible` and the reason is explained in this thread from `react-spectrum` https://github.com/adobe/react-spectrum/issues/1247
`onPress` is not exposed as a prop
`onPress` is now exposed as a prop
=> feat(CTA): add react-aria useButton

src/component-library/TokenStack/TokenStack.stories.tsx, src/component-library/TokenStack/TokenStack.style.tsx, src/component-library/TokenStack/TokenStack.tsx, src/component-library/TokenStack/index.tsx, src/component-library/index.tsx
For AMM, we will need to handle up to 4 tokens, which is not possible with the current `CoinPair`. Changing it do address this feature would open doors for breaking changes, as well as regressions.
This new component contains features like `offset`, where you can increase or decrease the offset of each token. Useful when there is a need to preserve space.
=> feat(TokenStack): add component

src/utils/hooks/api/use-get-prices.tsx
We need prices to be refetched on each new block.
Refetch was set to 60 sec
Refetch set to block time (12 sec)
=> feat: set prices refetch interval to block time

src/utils/constants/currency.ts
When dealing with currencies, we should not mix native currencies from Interlay with Kintsugi, and vice-versa. 
Currently we mix them, leading us to query data using currencies that are not native to that parachain.
Separate these native currencies 
This data is used primarily for `useGetCurrencies`, which is used by `useGetBalances` and `useGetPrices`. So, this change affects the whole app.
=> fix: native currencies constant

package.json, src/pages/Loans/LoansOverview/components/LendPositionsTable/LendPositionsTable.tsx, src/pages/Loans/LoansOverview/components/LoansInsights/LoansInsights.tsx, src/utils/hooks/api/loans/use-get-account-positions.tsx, yarn.lock
Remove `earnedInterest` from Loans page
Loans page displays user earned interest in USD
Temporarily removed it, leave only the net apy.
- Create lend positions and borrow positions
=> fix(Loans): remove earnedInterest

src/component-library/Input/BaseInput.tsx, src/component-library/Input/Input.style.tsx, src/component-library/TokenInput/TokenInput.stories.tsx, src/component-library/TokenInput/TokenInput.style.tsx, src/component-library/TokenInput/TokenInput.tsx, src/component-library/TokenInput/TokenList.tsx, src/component-library/TokenInput/TokenSelect.tsx, src/component-library/TokenInput/index.tsx, src/component-library/TokenStack/TokenStack.style.tsx, src/component-library/TokenStack/TokenStack.tsx, src/component-library/theme/theme.kintsugi.css
These are some improvements found during swap and pools development. Also added concept of `SingleToken` & `MultiToken` (for LP Tokens)
- We programatically declared padding to avoid input overlapping the right adornment.
- Bad state handling
- Uses a ref to determined the needed spacing 
- checks better for state changes by only reacting to when prop is different than `undefined`
=> fix(TokenInput): state, input padding and list

src/components/AuthCTA/AuthCTA.tsx, src/components/AuthCTA/index.tsx
The purpose of this component is to have a button that has 2 states:
- `No Auth`: the button will have the text `Connect` and by clicking in it, the modal to select account will appear. Any kind of behaviour passed to it, wont be executed.
- `With Auth`: the button regains the intended behaviour.
=> feat: add AuthCTA

src/component-library/CoinIcon/CoinIcon.style.tsx, src/component-library/CoinIcon/CoinIcon.tsx, src/component-library/Input/Input.style.tsx, src/component-library/Modal/Modal.style.tsx, src/component-library/Modal/Modal.tsx, src/component-library/TokenInput/TokenInput.style.tsx, src/component-library/TokenInput/TokenList.tsx, src/component-library/TokenInput/TokenListModal.tsx, src/component-library/theme/theme.ts
1. Add fallback icon to `CoinIcon`
2. Add `hasMaxHeight` to `Modal`
3. Handle text overflow scenarios on TokenInput select adornment and also list. 
1. No fallback icon
2. Modal occupies whole screen
3. Many text overflows
All scenarios are covered
AMM
=> fix: TokenInput, Modal props and CoinIcon fallback icon

src/pages/AMM/Pools/components/DepositForm/DepositForm.tsx
Field validation was showing after form submit on depositing liquidity
Showing error after form submission 
Hiding error after form submission 
Pools AMM
=> fix(Pools): hide validation error after submit

src/component-library/TokenInput/TokenInput.tsx
Javascript do not handle very well decimals.
In this situation, when I apply max balance, it applies an exponential value, which is not validated correctly.
This PR aims to avoid applying exponential and just the full number.
Applies exponential 
Applies normal number
=> fix(TokenInput): apply balance decimal issue

package.json, src/pages/AMM/Pools/Pools.tsx, src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx, src/pages/AMM/Pools/components/PoolsInsights/utils.ts, src/pages/AMM/Pools/components/PoolsTables/PoolsTable.tsx, src/pages/AMM/Pools/components/PoolsTables/utils.ts, src/utils/hooks/api/amm/use-get-account-pools.tsx, yarn.lock
Adding farming to AMM - displaying APR, claimable rewards and adding button to claim all farming rewards. Updating lib to `0.32.5`
n/a
New features added
Check if APRs are correct. Create LP position on pool that has reward activated in farming pallet. Wait for a bit and check if claimable rewards are starting to show up. Click on claim button and check that transaction is successful and rewards are added to testing account.
=> feat(amm): add farming

src/index.tsx, src/pages/AMM/Pools/components/DepositForm/DepositForm.tsx, src/pages/AMM/Pools/components/PoolsBaseTable/BalanceCell.tsx, src/pages/AMM/Pools/components/WithdrawForm/WithdrawForm.tsx, src/pages/AMM/Swap/components/SwapInfo/SwapInfo.tsx, src/pages/Loans/LoansOverview/components/LoansBaseTable/BalanceCell.tsx
Config `Big` to handle better big decimals (copied `monetary` config).
Fixed places where rounding was too aggressive.
Liquidity should not be 0
=> fix: Pools and Loans cells formatting

src/component-library/TokenInput/TokenInput.tsx, src/component-library/TokenInput/TokenInputBalance.tsx, src/component-library/TokenInput/TokenInputLabel.tsx, src/component-library/TokenInput/TokenList.tsx, src/index.tsx, src/pages/AMM/Pools/components/DepositForm/DepositForm.tsx, src/pages/AMM/Pools/components/WithdrawForm/WithdrawForm.tsx, src/pages/AMM/Swap/hooks/use-swap-form-data.tsx, src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx, src/pages/Vaults/VaultsOverview/components/CreateVaultWizard/DespositCollateralStep.tsx
We have been facing quite a lot of issues with big decimals turning into exponential numbers. This PR aims to remove any kind of formatting happening in the `TokenInput`, since a better approach was found: config `Big` to output strings without exponentials. To safely handle this the following changes were made:
1. `balance` - from being just `number` -> `string | number`: turning amounts into numbers will make them exponential, so we now allow both types.
2. `humanBalance` - new prop which will be used to display balance in a shorter version. The difference is that `humanBalance` is just for display and `balance` is to be used programmatically.
3.  Remove old temporary code that was handling decimals issues.
4. Made changes across every form using `TokenInput` to include these latest …
=> fix(TokenInput): token input decimals handling

src/common/utils/utils.ts, src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx, src/utils/hooks/api/loans/use-loan-mutation.tsx
Error modal on loan form, when closed, closes both modals. Also added AuthCTA to LoanForm.
Error modal on loan form, when closed, closes both modals.
Moved the error to a toast, just like we have in amm.
Lending
=> fix: remove error modal and add auth cta

src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx
We should check if the user is trying to `replayAll` or `withdrawAll` on their asset. We do so, by debouncing the user input and check if the input amount equals the max available to withdraw/repay.
Can only max repay or withdraw by clicking balance
We handle both clicking balance and typing exactly the amount.
Lending (withdraw/repay all funds)
=> fix(Loans): check input max value on loan forms

src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx, src/pages/AMM/Swap/hooks/use-swap-form-data.tsx, src/pages/AMM/shared/utils.ts
There were a couple of tokens that should not be listed in the swap page.
All existing on chain currencies were being displayed 
Only currencies that belong to a pool will be displayed
Swap
=> fix(Swap): filter out unwated tokens

src/utils/hooks/use-copy-to-clipboard.tsx
Fixes #864 
The copy action is not possible because it takes you to the vaults page once you click it.
The address is copied, and navigating does not happen if you click the copy icon.
- Go to `/dashboard/vaults`.
- Click on an address copy icon at the vaults table.
- The address is copied, and navigation does not happen but if you click outside of the icon, it takes you to the vault page instead of having that address copied.
=> fix: add event.stopPropagation to handleCopyToClipboard

package.json, src/lib/form-validation/loans/lend.ts, src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx, src/pages/Loans/LoansOverview/hooks/use-loan-form-data.tsx, src/pages/Loans/LoansOverview/utils/get-max-borrowable-amount.tsx, src/pages/Loans/LoansOverview/utils/get-max-lendable-amount.ts, src/utils/helpers/currencies.ts, yarn.lock
Adding supply and borrow caps into loans calculations.
Caps were not taken into account before which caused some errors.
Loan form is validated using caps and maximum computation methods are adjusted.
Go to loans page. Find a pair that is close to supply or borrow cap and check that Loan form is displaying and validating correct amount.
=> feat: take supply and borrow caps into account

src/legacy-components/TestnetBanner/index.tsx
Changes the current testnet banner to notify users that testnet is currently offline and points them to our discord.
Got to any testnet page and see the updated banner.
=> hotfix: testnet banner

public/index.html
Added an embedded Discord chat using [Widgetbot](https://docs.widgetbot.io/embed/crate/tutorial/#getting-started) <script> tag in index.html. 
This functions as a live chat using our Discord server (uses trollbox public chat which has stricter MEE6 moderation rules for non-verified members).  
No embedded chat 
Discord icon in the bottom right of the screen.  
When clicked, loads Discord connection and opens the "trollbox" channel (can be set to any channel). 
User can then chat with each other while using the app via our Discord server. 
See Loom video: https://www.loom.com/share/46fed094ad1a4afd825473462f1f82f1
=> feat: added Discord chat embed

src/pages/Loans/LoansOverview/hooks/use-get-ltv.tsx
Fix loan status resolution by using LTV in percentage denomination.
=> fix(loans): use ltv in percentage denomination to resolve loan status

src/pages/Loans/LoansOverview/components/BorrowLimit/BorrowLimit.style.tsx, src/pages/Loans/LoansOverview/components/BorrowLimit/BorrowLimit.tsx, src/pages/Loans/LoansOverview/components/BorrowLimit/RemainingDebt.tsx, src/pages/Loans/LoansOverview/components/LoanActionInfo/LoanActionInfo.tsx, src/pages/Loans/LoansOverview/components/LoanActionInfo/LoanGroup.tsx, src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx, src/pages/Loans/LoansOverview/hooks/use-loan-form-data.tsx
1. Change repay form to show on input label the amount the user has in his wallet that can be used to repay
2. Added a row in that form for the remaining debt
3. Removed unwanted APY showing on Withdraw and Repay form
Was using remaining debt as user balance
Now uses available balance correctly
1. Go to lending page
2. Open lend collateral positions and borrow positions
3. Try repaying loan after some blocks
=> fix(Loans): loan form ui and repay

src/component-library/Modal/Modal.tsx, src/component-library/Modal/ModalWrapper.tsx, src/component-library/Overlay/Overlay.style.tsx, src/component-library/Overlay/Overlay.tsx, src/pages/AMM/shared/components/SlippageManager/SlippageManager.tsx
- Missing props for Modal Wrapper
- Add `isolate` property to our OverlayWrapper (https://developer.mozilla.org/en-US/docs/Web/CSS/isolation)
- Go to pool page
- Click top right cog and change slippage
- check if everything works
=> fix: missing Modal props and Overlay styles

src/component-library/TokenInput/TokenSelect.tsx, src/component-library/utils/input.ts, src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx
`onChange` was being trigger programmatically, but this kind of approach does not work on chrome mobile. This is due to the event `onSelectionChange` not being a native event but rather from `react-aria`
Swap
=> fix: TokenInput select

src/pages/Loans/LoansOverview/components/BorrowLimit/BorrowLimit.tsx, src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx, src/pages/Loans/LoansOverview/hooks/use-loan-form-data.tsx, src/pages/Loans/LoansOverview/utils/get-max-borrowable-amount.tsx, src/pages/Loans/LoansOverview/utils/get-max-lendable-amount.ts, src/pages/Loans/LoansOverview/utils/get-max-withdrawable-amount.tsx, src/test/pages/Loans/borrow.test.tsx, src/test/pages/Loans/index.test.tsx, src/test/pages/Loans/repay.test.tsx, src/test/pages/Loans/withdraw.test.tsx
- There was a lot of code that needed refactoring.
- The problem was in the `isEqualBalance`, because I was using this to determine wether the user was repaying the full loan.  I was passing the wrong parameters. 
-  removed unwanted liquidation alert on repay form and only showed it when user had some input interaction
the problem: https://github.com/interlay/interbtc-ui/pull/1050/files#diff-1d81792feeb73f0344f796b7a435c46cf3761479ecaa8e640e1efff5dedeb35cL120
I should have not passed `assetBalance` but instead the `balance` field assigned above.
=> fix(Loans): loan form

package.json, src/index.tsx, yarn.lock
Revert sentry config—causing issues with production site. Will investigate more closely post launch.
=> refactor: revert sentry config

src/legacy-components/AddressWithCopyUI/index.tsx, src/legacy-components/IssueUI/BTCPaymentPendingStatusUI/index.tsx
Quick fix to show full BTC address for issue modal. The component which handles this is widely used, so to avoid making lots of changes I've added a `shortenAddress` prop which defaults to true (and will maintain existing behaviour).
=> Show full BTC address on issue modal

src/pages/AMM/Pools/components/DepositForm/DepositForm.tsx, src/test/pages/Pools.test.tsx
Adds custom input amounts mode for Pools
Each input is set with pool ratio
When the user touches a second input, he enter custom input amounts mode
1. Go to pools page
2. Open a pool
3. Input amount on first input
4. See that second gets affected
5. Input Amount on second input
6. See that first input **is not** affected
=> feat(Pools): add custom input amounts mode

.github/workflows/chromatic.yml, .github/workflows/yarn-test.yml
`on: [push, pull_request_target]`
This was making the pipeline run the test in the PR branch (`push`) and also in the `master` branch (`pull_request_target`)
The new config:
```
on:
push:
pull_request:
workflow_dispatch:
```
Makes the tests run only once against the desired branch. Also added `workflow_dispatch` because it will allow us to manually trigger running tests against a certain branch (https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
=> chore: fix test workflow

package.json, src/store.ts, yarn.lock
- `polkadot` packages warning messages is solve by adding resolutions for the packages in those warning (https://substrate.stackexchange.com/questions/2399/how-to-prevent-remove-duplicate-modules-and-mismatched-version-numbers-i-e)
- `companion-bubble.js` error and blur error is caused by loom, which you can disable and enable whenever you need it.
- removed `redux-logger` since we are moving away from it and I dont use (might be biased)
=> fix: console warnings

src/legacy-components/Tokens/TokenSelector/index.tsx
In the top right token selector, the selected token shows the total balance, not the transferable balance. The correct value is shown in the drop down.
Previous behaviour:
Fixed behaviour:
Check that the values match.
=> Fix: show transferable balance for selected currency

package.json, src/pages/Staking/LockTimeField/index.tsx
There are two issues fixed in this PR, [OG ISSUE](https://github.com/interlay/interbtc-ui/issues/940)
1. When you enter more than 3 digital in the lockin time field of staking tab, one digit is cut off
2. User messaging is confusing—it implies 192 extra weeks, rather than total weeks
1. Supports 3 digits
2. Improved UX sensibility by changing the text
1. Enter three digits in lockin field of staking tab
=> Fix input field width issue

src/pages/Staking/index.tsx
Lock time extension was being calculated incorrectly, and generating an incorrect APY value 
Check staking UI values
=> refactor: use current block when calculating lock time extension

src/pages/Staking/index.tsx
Fix APY calculation when extending lock time
APY is calculated using `currentBlockNumber + convertWeeksToBlockNumbers(lockTimeValue)`
APY should be calculates using `stakedAmountAndEndBlock.endBlock + currentBlockNumber + convertWeeksToBlockNumbers(lockTimeValue)`
Check that APY calculation is correct
=> fix: correct apy calculation

package.json, src/pages/Staking/index.tsx
=> [release] Kintsugi 2.9.5

src/pages/Staking/index.tsx
This PR prevents the estimated staking rewards from being fetched when the form is in error. It's not an ideal fix—the refetch function is being called from the component body. Unfortunately there is a race condition when using `useEffect` which mean that the RPC call was being made before it could be disabled. This is an underlying issue with the component design, and not easily resolvable.
=> [staking] Handle RPC error

src/pages/Staking/index.tsx
Calculate apy and rewards when staking with no existing stake
=> fix: use currentBlockNumber when there is no existing stake

package.json, src/config/relay-chains.tsx, src/pages/Staking/index.tsx
=> [release] Kintsugi 2.30.5

src/component-library/TokenInput/TokenInput.stories.tsx, src/component-library/TokenInput/TokenInput.tsx
When we have a dynamic token list (as with XCM transfers) we don't want to use logic in the pages to pass through either a ticker of a list of tokens via select props. Instead, we want the token input to handle a single item array exactly as it would a ticker.
Note: we still require the ticker prop. For most of our use cases, the token list is immutable. However, the list of tokens being passed in through the XFM transfer page will change when the to and from destinations are updated.
Disable select if only a single token is passed in via `selectProps`
Select is enabled
Select is disabled, with token adornment being shows instead.
Can be seen in storybook—not currently used in production
=> [tokenInput] support single-item array

src/utils/hooks/use-sign-message.ts
Reset sign terms mutation on account change
Account A mutation would show up on Account B
Mutation is reset on wallet change
- with 2 accounts without signatures, start a signature on one but dont confirm on the wallet. Switch to the other account and you should be able to see the accept & sign button enabled.
=> fix: reset sign terms mutation on account change

package.json, src/components/LoanPositionsTable/LoanPositionsTable.tsx, src/pages/Loans/LoansOverview/components/BorrowAssetsTable/BorrowAssetsTable.tsx, src/pages/Loans/LoansOverview/components/LendAssetsTable/LendAssetsTable.tsx, src/pages/Loans/LoansOverview/components/LoansInsights/LoansInsights.tsx, src/test/mocks/@interlay/interbtc-api/parachain/loans.ts, src/utils/hooks/api/loans/use-get-account-lending-statistics.tsx, src/utils/hooks/api/loans/use-get-account-subsidy-rewards.tsx, yarn.lock
#description
Display correct incentive rewards, lib update to `2.2.1`.
Dapp was displaying incorrect amount that is used to compute average APY.
Total reward amount is computed more precisely and reward per market is fixed.
1. Lend or borrow asset with active rewards
2. Check that rewards are changing on block-by-block basis 
3. Check particular rewards in asset tooltip
4. Check that claimed reward amount corresponds to displayed amount.
=> fix(loans): display correct incentive rewards

src/components/LoanPositionsTable/ApyCell.tsx, src/components/LoanPositionsTable/LoanPositionsTable.tsx, src/pages/Loans/LoansOverview/components/BorrowAssetsTable/BorrowAssetsTable.tsx, src/pages/Loans/LoansOverview/components/LendAssetsTable/LendAssetsTable.tsx
Fix lending incentive reward APY computation in tables.  With the latest upgrade, the accrued rewards computation was fixed, but that introduced new bug in APY computation. Now both are fixed by using correct data source for computation. New property was added to `ApyCell` component to make it explicit what `reward` data is being passed so no more similar errors are made again. 
APY computation in tables is fixed.
=> fix(loans): use correct data for computation of incentive rewards APY in tables

src/components/Geoblock/Geoblock.tsx, src/config/links.ts, src/index.tsx, src/utils/hooks/use-geoblocking.ts
Adding geoblocking.
Access from all countries was enabled.
Users from forbidden countries will be redirected if they try to access the dapp.
=> feat: redirect when access from forbidden country is detected

src/pages/Transfer/CrossChainTransferForm/CrossChainTransferForm.tsx
This is a temporary fix—at the moment the account selector is only used on the XCM form. When it's refactored to use the updated select component and to allow manual input, this should be handled in the component for consistency across the application.
This changes the behaviour so that if a used changes account using the account selector in the top bar, the selected XCM account is changed to that account. At the moment it remains set to the previously selected account.
=> refactor: reset selected account on account change

src/components/LoanApyTooltip/BreakdownGroup.tsx, src/pages/Loans/LoansOverview/components/LoanActionInfo/RewardsGroup.tsx, src/utils/helpers/loans.ts
Incentive rewards APR was not converted to percentage when displayed. Now fixed and APY changed to APR for incentive rewards.
=> hotffix kintusgi: add percentage conversion

src/component-library/TokenInput/TokenInput.tsx
Passing wrong value to the non-select adornemnt.
TokenAdornment does not handle Lp tokens tickers
Now handles
Go to withdraw form on pools page.
=> fix(TokenInput): adorment ticker

src/components/NotificationsPopover/NotificationsList.tsx
Notifications need to be sorted from newest to oldest
Before
After
=> fix: sort notifications

api/market_data.py, package.json, src/components/LoanPositionsTable/ApyCell.tsx, src/pages/AMM/Pools/components/DepositForm/DepositOutputAssets.tsx, src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx, src/parts/Topbar/index.tsx, src/utils/helpers/loans.ts, yarn.lock
=> [release] Kintsugi 2.34.0

src/pages/Wallet/WalletOverview/components/WalletInsights/WalletInsights.tsx
Closes #1316 
Discussed with Dom and Sander—we've removed the code which added the lend positions as lend positions are already included in balance.reserved, which is taken into account when calculating the raw balance (i.e. we were counting lend positions twice).
There are still minor discrepancies when manually adding the figures together, but these are low dollar amounts and caused by rounding and/or exchange rate fluctuations.
In this account, available assets + lend positions - borrow positions + liquidity pools + staked = 46176.67 which is very close to the total balance. (Note that SKSM and USDT have small amounts available, with the dollar amount rounded to 0; these will be included in the total balance as shown in the insights box. Other dollar amounts will also be rounded.)
=> fix: correct wallet balance

src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/AvailableAssetsTable.tsx
Add default assets to the wallet page, i.e. some assets are shown even at zero balance.
=> [wallet] add default currencies to wallet

src/pages/Transfer/TransferForms/TransferForms.tsx, src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/ActionsCell.tsx
Correct query parameter. I've reverted to having 'crossChainTransfer' as the URL, as there may be inbound links (the previous version of the xcm tab could be accessed directly at http://app.interlay.io/transfer/?tab=crossChainTransfer). We'll update this when we handle #1354.
Closes #1365
=> [transfer/bridge] open correct tab

src/lib/form/schemas/swap.ts
Validation was breaking when you select `from` token after the whole form is filled
=> fix(Swap): handle when schema params are undefined

src/pages/Vaults/Vault/VaultDashboard.tsx, src/utils/hooks/api/vaults/get-vault-data.ts
The code assumed that ratio would be 0..1 while it was actually 0..100: https://github.com/interlay/interbtc-ui/blob/52ffd0dabf860650029d25bde1eeaeec2036059b/src/utils/hooks/api/vaults/get-vault-data.ts#L79
Closes https://github.com/interlay/interbtc-ui/issues/736
Closes https://github.com/interlay/interbtc-ui/issues/1439
=> fix: use correct value for vault capacity indicator

api/market_data.py
If an asset is not defined on https://www.diadata.org/ then we fallback to retrieving its price from coingecko.
=> api: add fallback to coingecko for missing assets on dia

src/App.tsx
Redirect seems to be flaky—sometimes resolves to the wallet page, sometimes not. We haven't changed this for a while, so not sure what's caused it to become an issue now (unless it was an existing issue we hadn't picked up).
Alternative way of handling this is to use an array in the Route path, rather than a redirect; this seems to be working consistently.
=> [app] Use route instead of redirect

src/components/SlippageManager/SlippageManager.tsx
Adds a zero % slippage option. Note that the decision to add this has not been signed off  by anyone. I just added it because I personally needed this feature, I'm using the preview for now. I tested and it seems to work fine. The default value is still 0.1%
=> feat: zero slippage option

src/App.tsx
Closes #1518 
Found a much quicker fix. Our implementation was using `<Redirect to={} from={} />` which was being inconsistent. Router v5 documenation suggests using a nested route:
```
<Route ... >
<Redirect>
</Route>
````
This has fixed the problem without needing to bump the version of React Router.
=> fix: use redirect in route

src/hooks/api/use-get-dex-volume.tsx
=> fix: use-get-dex-volumes hook

src/pages/Pools/components/DepositForm/DepositForm.tsx, src/test/pages/Pools.test.tsx
Custom ration on inputs was leading a lot of users to failing transactions
Changing input A and then customising the input B leads leads to custom ratio 
Pool ratio is always applied
> go to pools
> open deposit modal
> Change input A
> change input B
> See that input A is changed to current ratio
=> fix(Pools): remove ratio customization

src/pages/Dashboard/cards/OracleStatusCard/index.tsx
Fix with minimal changes—not ideal, as we're getting the exchange rate for the card/table in two different ways. Long term, we need to refactor to pass this value down from a parent component or state, but this PR is ok within the context of fixing the bug.
=> fix: correct exchange rate

package.json
Set NODE_OPTIONS to enable legacy SSL support. This is required to build with Node 18. Have tested on Interlay testnet and it works fine, so I've updated the settings for all four environments. This PR will need to be merged before any others, otherwise builds will fail.
Closes #1546
=> wip: try setting node options in package

src/config/links.ts, src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/ActionsCell.tsx, src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/AvailableAssetsTable.tsx, src/utils/constants/currency.ts
=> feat(Wallet): add bitforst token swap link

api/currency-utils.js, api/package-lock.json, api/package.json, api/tvl_dex.js, api/tvl_loans.js, package.json, src/hooks/api/bridge/use-get-issue-request-limits.tsx, src/pages/BTC/BTCOverview/components/IssueForm/IssueForm.tsx, src/pages/Dashboard/cards/CollateralizationCard/index.tsx, src/services/fetchers/oracle-exchange-rates-fetcher.ts, vercel.json, yarn.lock
=> [release] Kintsugi 2.41.0

src/pages/SendAndReceive/SendAndReceiveForms/components/BridgeForm/BridgeForm.tsx
See:
https://github.com/interlay/interbtc-ui/issues/1644
https://discord.com/channels/745259537707040778/1210509457902018600
This will be fixed in the bridge next week at which point this code change will be reverted.
=> hotfix: XCM polkadot/kintsugi max transferable balance

src/services/fetchers/cumulative-vault-collateral-volumes-fetcher.ts
Dashboard was crashing when certain data not available
To fix this, I added a question mark marking the variable as possibly undefined
=> Fixed a small dashboard display issue

package.json, src/App.tsx, src/components/AppAlert/AppAlert.styles.tsx, src/components/AppAlert/AppAlert.tsx, src/components/AppAlert/index.tsx, src/components/Layout/Layout.tsx, src/hooks/use-local-storage.ts, src/lib/form/schemas/bob.ts, src/lib/form/schemas/index.ts, src/lib/form/validate.ts, src/lib/form/yup.custom.ts, src/pages/BOB/BOB.styles.tsx, src/pages/BOB/BOB.tsx, src/pages/BOB/index.tsx, src/utils/constants/links.ts, yarn.lock
=> [release] kintsugi/2.41.16

src/App.tsx, src/hooks/use-feature-flag.ts, src/pages/BOB/BOB.tsx
=> Feature flag
