- .env.kintsugi
- src/App.tsx
- src/assets/locales/en/translation.json
- src/constants.ts
- src/pages/Transfer/TransferForm/index.tsx
- src/parts/AccountModal/index.tsx
- src/parts/Topbar/index.tsx
> hotfix activate transfer

- src/pages/Dashboard/sub-pages/BTCRelay/BlocksTable/index.tsx
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>
> fix: parse index payload for block hashes

- public/interlay/site.webmanifest
- public/kintsugi/site.webmanifest
- src/config/relay-chains.tsx
@crypto-engineer this changes the app name from kBTC to KINT. Think I've made all the relevant changes, but let me know if I've missed any.
> fix: correct app name

- src/parts/Sidebar/SidebarContent/Navigation/index.tsx
Note: can't be merged into master as that branch doesn't have the disabled navigation commit. PR goes into kintsugi branch.
Bumps transfer to the top of the list
> chore: move transfer nav item to top of nav

- package.json
- src/App.tsx
- yarn.lock
- Upgrade @interlay/interbtc.
- Update some parts for breaking changes.
> feat: upgrade @interlay/interbtc (1.5.6 to 1.5.7)

- src/assets/locales/en/translation.json
- src/pages/Vault/UpdateCollateralModal/index.tsx
Small fix to validate withdrawal against collateral rather than amount held by account.
> fix: validate vault withdrawal against max withdrawal amount

- package.json
- src/pages/Staking/index.tsx
- yarn.lock
- Accounts for the new locktime to estimate APY and rewards
> fix: account for locktime in APY calculation

- src/pages/Vault/VaultRedeemRequestsTable/index.tsx
Was showing as 0, should show properly now
> Fix vault redeem table amount column

- src/pages/Staking/index.tsx
> fix: correct validateLockingAmount

- package.json
- src/assets/locales/en/translation.json
- src/pages/Dashboard/sub-pages/Vaults/VaultsTable/index.tsx
- src/pages/Vault/index.tsx
- src/parts/Sidebar/SidebarContent/Navigation/index.tsx
- src/utils/constants/links.ts
- yarn.lock
- Rename `VAULT_ADDRESS` as `VAULT_ACCOUNT_ADDRESS`.
- Rename `vaultId` as `vaultAccountId`.
- Integrate `react-error-boundary` into the Vault page.
- Rename polkaBTC as interBTC.
- Integrate `getGovernanceReward` API.
- Clean up the vault page a little.
> feat: governance token earned card in the vault dashboard

- src/pages/Staking/index.tsx
hi @alexeiZamyatin - very rough bit of code until Anton comes back online. Looks like this:
> feature: temp notification

- src/pages/Staking/index.tsx
Same PR :) - slightly different layout as kintsugi is behind master.
This is a hotfix from the Kintsugi branch, but any merge conflicts with master when we merge in the component proper should be very easy to resolve as this is a single file change.
> fix: add info component to kintsugi

- src/components/WarningBanner/WarningBanner.stories.tsx
- src/components/WarningBanner/index.tsx
- src/pages/Staking/index.tsx
- src/utils/constants/styles.ts
A follow-up to https://github.com/interlay/interbtc-ui/pull/212.
> feat: add WarningBanner to Staking

- api/requirements.txt
- api/supply_info.py
- vercel.json
- https://interbtc-ui-interlay-git-supplyinfo-interlay.vercel.app/supply/kint-circ-supply
- https://interbtc-ui-interlay-git-supplyinfo-interlay.vercel.app/supply/kbtc-supply
- https://interbtc-ui-interlay-git-supplyinfo-interlay.vercel.app/supply/kint-total-supply
SUBSCAN_API_KEY is set to a dummy value in Vercel.
> Add supply-info serverless function

- api/requirements.txt
- api/supply_info.py
- vercel.json
> feat: merging supply info into kintsugi

- src/pages/Dashboard/sub-pages/IssueRequests/IssueRequestsTable/index.tsx
- src/pages/Dashboard/sub-pages/RedeemRequests/RedeemRequestsTable/index.tsx
- src/pages/Transactions/IssueRequestsTable/IssueRequestModal/IssueRequestStatusUI/ReceivedIssueRequest/index.tsx
- src/pages/Transactions/IssueRequestsTable/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/DefaultRedeemRequest/index.tsx
- src/pages/Transactions/RedeemRequestsTable/index.tsx
- src/pages/Vault/VaultIssueRequestsTable/index.tsx
- src/pages/Vault/VaultRedeemRequestsTable/index.tsx
- src/services/fetchers/issue-request-fetcher.ts
- src/services/fetchers/redeem-request-fetcher.ts
- src/services/fetchers/request-btctx-fetcher.ts
Instead of only after the bitcoin confirmations are fulfilled.
Also simplified the issue/redeem fetchers accordingly.
> fix: display parachain confirmations as they come in

- src/assets/locales/en/translation.json
- src/pages/Bridge/IssueForm/index.tsx
> feat: add Transaction Fee field to IssueForm

- package.json
> chore: update UI version

- src/assets/locales/en/translation.json
- src/pages/Bridge/IssueForm/index.tsx
We're going to hold off on merging this. Bug fix is working, but we've hit some related user messaging issues. We have a task to fix that, but we need to push both fixes at the same time so it makes sense to handle the related issues in a single PR. 
~~Very small fix for this - was passing in an invalid property. We have a type issue (which is why I wasn't stopped from passing in the invalid property!) but this is on the lib side. Once this is fixed in the lib we may need to add stronger typing in the UI, but the lib fix needs to be done first.~~
> issue bug and user messaging

- src/pages/Staking/index.tsx
- Fix the max extendable lock time.
- Fix other relevant UX displaying issues.
- Improve the relevant implementation.
> fix: correct max weeks for staking

- package.json
- yarn.lock
- fixes replace request ID display
- tweaks griefing collateral calculation on Issue
> chore: bump lib

- src/parts/Sidebar/SidebarContent/Navigation/index.tsx
Fixing hidden sidebar when the wallet is not connected.
> fix: show sidebar when wallet not connected

- src/pages/Dashboard/sub-pages/Oracles/OraclesTable/index.tsx
> feat: configure with BTCToCollateralTokenRate

- .env.kintsugi
- .env.testnet
- src/services/fetchers/generic-fetcher.ts
This is a minor PR for clean-up.
> chore: clean up

- src/pages/Vaults/Vault/index.tsx
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>
> fix: vault page showing incorrect vaultid

- src/App.tsx
- src/common/types/util.types.ts
- src/common/utils/utils.ts
- src/pages/Bridge/BurnForm/index.tsx
- src/pages/Bridge/IssueForm/index.tsx
- src/pages/Bridge/RedeemForm/SubmittedRedeemRequestModal/index.tsx
- src/pages/Bridge/RedeemForm/index.tsx
- src/pages/Dashboard/cards/CollateralLockedCard/index.tsx
- src/pages/Dashboard/sub-pages/Home/WrappedTokenCard/index.tsx
- src/pages/Dashboard/sub-pages/IssueRequests/UpperContent/index.tsx
- src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/index.tsx
- src/pages/Staking/index.tsx
- src/pages/Transactions/IssueRequestsTable/IssueRequestModal/BTCPaymentPendingStatusUI/index.tsx
- src/pages/Transactions/IssueRequestsTable/IssueRequestModal/WhoopsStatusUI/index.tsx
- src/pages/Transactions/IssueRequestsTable/IssueRequestModal/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/ReimbursedRedeemRequest/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/RetriedRedeemRequest/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/ReimburseStatusUI/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/index.tsx
- src/pages/Transfer/CrossChainTransferForm/index.tsx
- src/pages/Vaults/Vault/RequestIssueModal/index.tsx
Merge https://github.com/interlay/interbtc-ui/pull/313 into Interlay branch.
> Merge into Interlay: handling of CG undefined values

- src/config/vaults.ts
Adding config of vault collaterals for Interlay
> fix: added missing vault collateral config for interlay

- src/App.tsx
- src/common/reducers/general.reducer.ts
- src/common/types/util.types.ts
- src/pages/Bridge/BurnForm/index.tsx
- src/pages/Bridge/RedeemForm/index.tsx
- src/pages/Dashboard/sub-pages/Home/LockedCollateralsCard/index.tsx
- src/pages/Dashboard/sub-pages/Vaults/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/ReimbursedRedeemRequest/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/RedeemRequestStatusUI/RetriedRedeemRequest/index.tsx
- src/pages/Transactions/RedeemRequestsTable/RedeemRequestModal/ReimburseStatusUI/index.tsx
- src/pages/Transfer/CrossChainTransferForm/index.tsx
Rename collateralToken to relayChainNativeToken in Prices object
> refactor: add relayChainNativeToken to Prices type

- package.json
> chore: bump UI version

- src/components/Ring64/index.tsx
- src/pages/Dashboard/cards/OracleStatusCard/index.tsx
> Improve OracleStatusCard by adding market pair on own line

- src/componentLibrary/Balance/Balance.stories.tsx
- src/componentLibrary/Balance/Balance.style.tsx
- src/componentLibrary/Balance/Balance.tsx
- src/componentLibrary/Balance/index.tsx
- src/componentLibrary/index.tsx
Adding simple balance element to component library.
> feat: balance element

- src/pages/Vaults/index.tsx
- src/utils/hooks/api/get-vault-overview.ts
> fix: get pending redeems

- src/componentLibrary/Balance/Balance.style.tsx
- src/componentLibrary/CTA/CTA.style.tsx
- src/componentLibrary/Icon/Icon.style.tsx
- src/componentLibrary/InfoBox/InfoBox.style.tsx
- src/componentLibrary/Modal/Modal.style.tsx
- src/componentLibrary/NewVaultsTable/NewVaultsTable.style.tsx
- src/componentLibrary/Table/Table.style.tsx
- src/componentLibrary/VaultCard/VaultCard.style.tsx
- src/componentLibrary/theme/theme.base.css
- src/componentLibrary/theme/theme.interlay.css
- src/componentLibrary/theme/theme.kintsugi.css
- src/componentLibrary/theme/theme.ts
- Refactoring and fixing component library color variables 
- Defining font family globally for component library
> refactor: refactored component library colors and globally defined font

- src/pages/Staking/index.tsx
Quick fix of the transaction fee amount for the Interlay staking. Merge directly into Interlay branch.
> fix: quickfix of staking tx fee amount

- .lintstagedrc.js
Make it so that `prettier` is run automatically.
> feat: add prettier to lint-staged

- src/component-library/Icon/Icon.stories.tsx
Add missing story to Storybook
> chore: add missing icon story

- src/components/Accounts/index.tsx
**Ticket:** [url](https://www.notion.so/interlay/d6d38c0a0ec74579a8b0ea3830af088b?v=b3f681fbc47c4173805c9e6db808f8ad&p=e4a41d6147b34b5bb1c74dd5fa98b74a)
**Description:** Make current account as default destination for cross chain transfer
> feat(transfer): make current account as default destination

- .env.dev
- src/assets/locales/en/translation.json
- src/parts/Sidebar/SidebarContent/index.tsx
1. added new env variables for app version and name
2. added version to sidebar footer using env variable
> feat(sidebar): add UI version to footer

- src/App.tsx
- src/pages/Vaults/Vault/index.tsx
- src/pages/Vaults/index.tsx
- src/parts/Sidebar/SidebarContent/Navigation/index.tsx
- src/utils/hooks/api/get-vault-overview.ts
Quick fix to handle showing registered vaults with oracles offlline
> fix: allow vaults to work with oracle offline

- src/component-library/Stack/Stack.stories.tsx
- src/component-library/Stack/Stack.style.tsx
- src/component-library/Stack/Stack.tsx
- fixed styles
- added more flexibility in terms of the component semantics and future use for accessibility
> fix(Stack): styles and props

- src/config/links.ts
Adding external links to Interlay sidebar.
> fix: add external links

- package.json
- yarn.lock
Updating lib version from 1.13.5 to 1.13.6
> chore: update lib version 1.13.5 -> 1.13.6

- src/pages/Dashboard/sub-pages/IssueRequests/IssueRequestsTable/index.tsx
Need double-checking on vercel preview before merging
> feat: add display of BTC tx for issue transactions to public dashboar……d page

- src/components/IssueUI/index.tsx
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>
> fix: use destination address for issue page

- src/component-library/Table/Table.stories.tsx
- src/component-library/Table/Table.style.tsx
- src/component-library/Table/Table.tsx
- src/component-library/Table/index.tsx
- improve types
- add padding between columns
> fix(Table): types and styles

- src/component-library/LoadingSpinner/LoadingSpinner.stories.tsx
- src/component-library/LoadingSpinner/LoadingSpinner.style.tsx
- src/component-library/LoadingSpinner/LoadingSpinner.tsx
- src/component-library/theme/theme.base.css
- src/component-library/theme/theme.interlay.css
- src/component-library/theme/theme.kintsugi.css
- src/component-library/theme/theme.ts
[Demo](https://www.loom.com/share/4a19d8527aff49cd8ac164119027c556)
> feat(LoadingSpinner): add indeterminate variant

- src/component-library/CTA/CTA.stories.tsx
- src/component-library/CTA/CTA.style.tsx
- src/component-library/CTA/CTA.tsx
- src/component-library/CTA/CTALink.stories.tsx
- src/component-library/CTA/CTALink.tsx
- src/component-library/theme/theme.ts
- src/component-library/utils/prop-types.ts
> feat(CTA): add size prop

- src/component-library/CollateralScore/CollateralScore.style.tsx
- src/component-library/CollateralScore/CollateralScore.tsx
- src/component-library/theme/theme.base.css
- src/component-library/theme/theme.interlay.css
- src/component-library/theme/theme.kintsugi.css
- src/component-library/theme/theme.ts
> feat: collateral score revamp

- package.json
- src/pages/Bridge/IssueForm/index.tsx
- src/pages/Dashboard/sub-pages/RedeemRequests/RedeemRequestsTable/index.tsx
- src/utils/helpers/vaults.ts
- src/utils/relay-chain-api/transfer-to-parachain.ts
- src/utils/relay-chain-api/transfer-to-relay-chain.ts
XCM bug fix and version bump ahead of release
> Version bump

- src/pages/Dashboard/cards/OracleStatusCard/index.tsx
- src/pages/Dashboard/sub-pages/Oracles/OraclesTable/index.tsx
- src/services/fetchers/cumulative-volumes-fetcher.ts
- src/services/fetchers/oracle-exchange-rates-fetcher.ts
- src/services/queries/issues-query.ts
- src/services/queries/redeems-query.ts
Rollout of this update should be coordinated with rollout of squid version 0.9.0 across the respective environments, to avoid breakage.
> feat: update for new squid currency schema

- src/pages/Vaults/Vault/VaultIssueRequestsTable/index.tsx
- src/pages/Vaults/Vault/VaultRedeemRequestsTable/index.tsx
- src/utils/hooks/api/get-vault-overview.ts
Follow up to #461, should be the last of it now
> fix: oversight, forgot to update a few squid queries

- src/pages/Dashboard/sub-pages/Vaults/VaultsTable/index.tsx
> fix: do not throw on dashboard for non-token collateral vault 

- package.json
- src/services/fetchers/request-btctx-fetcher.ts
> chore: get largest payment to recipient address for issue requests

- src/pages/Dashboard/cards/OracleStatusCard/index.tsx
Hotfix Oracle price on Kintsugi
> fix: construct exchange rate to return correct value

- src/component-library/CoinIcon/CoinIcon.tsx
- src/pages/Vaults/Vault/ReplaceTable/index.tsx
- src/pages/Vaults/Vault/VaultDashboard.tsx
- src/pages/Vaults/Vault/VaultIssueRequestsTable/index.tsx
- src/pages/Vaults/Vault/VaultRedeemRequestsTable/index.tsx
- src/utils/helpers/currencies.ts
- src/utils/hooks/api/vaults/get-vault-data.ts
Fixing support for foreign assets in reverted vaults table.
> refactor: fix for reverted vault table

- src/assets/locales/en/translation.json
- src/utils/helpers/vaults.ts
> fix: add translation entry and pass in correct text

- src/common/utils/utils.ts
Fix percentage utility to return correct value
> fix: percentage utility

- src/common/utils/utils.ts
Reverts interlay/interbtc-ui#514, which did not correctly fix % formatting issues.
> Revert "fix: percentage utility"

- src/pages/Vaults/Vault/UpdateCollateralModal/index.tsx
https://discord.com/channels/745259537707040778/956874224436391987/1021623019531153540
> fix: old update collateral modal collateralization

- src/pages/Vaults/Vault/components/VaultCollateral/VaultCollateral.tsx
- src/utils/hooks/api/vaults/get-vault-data.ts
> fix: multiply collateralization when fetched

- src/utils/hooks/api/vaults/get-vault-data.ts
Hotfix getIssuableTokens problem with liquidated vaults
> Hotfix/liquidated vaults error 

- src/pages/Vaults/Vault/VaultDashboard.tsx
- src/pages/Vaults/Vault/components/IssueRedeemForm/IssueRedeemForm.tsx
- src/pages/Vaults/Vault/components/VaultCollateral/VaultCollateral.tsx
Merge hotfix into release branch to avoid two releases
> fix: remove hardcoded wrapped ID strings

- README.md
- src/test/mocks/setup.ts
I had to debug for a bit so I could find out that I only needed to add `.env.test`. This might help whoever try to write tests in the near future.
> chore: update README.md and test setup

- src/component-library/Table/BaseTable.tsx
> fix(BaseTable): property errors

- src/assets/locales/en/translation.json
- src/components/IssueUI/BTCPaymentPendingStatusUI/index.tsx
- src/pages/Bridge/IssueForm/index.tsx
- src/pages/Bridge/RedeemForm/SubmittedRedeemRequestModal/index.tsx
- src/pages/Bridge/RedeemForm/index.tsx
> Hotfix/btc rounding Interlay

- src/App.tsx
- src/index.tsx
- src/lib/substrate/components/SubstrateLoadingAndErrorHandlingWrapper/index.tsx
- src/parts/ThemeWrapper/index.tsx
> Bugfix/loading UI background

- src/parts/Sidebar/SidebarContent/Navigation/index.tsx
- Updated icons after quick check with Jay
> fix: update icons according to input by Jay

- api/health.py
- api/requirements.txt
- vercel.json
Adds serverless function ran by Vercel. Returns state of various subsystems and can be used by Datadog or other monitoring systems.
> vercel serverless - add health check endpoints

- src/component-library/Input/BaseInput.tsx
- src/component-library/Input/Input.style.tsx
- src/component-library/NumberInput/NumberInput.tsx
- src/component-library/TokenInput/TokenInput.stories.tsx
- src/component-library/TokenInput/TokenInput.style.tsx
- src/component-library/TokenInput/TokenInput.tsx
- src/component-library/theme/theme.ts
- improvements to overflow logic
- introduce sizes
- disallow Spaces in NumberInput
- add decimals prop to TokenInput
> fix(TokenInput): changes to styled and BaseInput

- package.json
- yarn.lock
> chore(interlend): update lib version and enable preview deployments

- src/components/IssueUI/IssueRequestStatusUI/ManualIssueExecutionUI/index.tsx
Fix minor issues - text colour, button width
> Tom/manual issue execution UI

- src/lib/form-validation/index.ts
- src/lib/form-validation/loans/borrow.ts
- src/lib/form-validation/loans/index.ts
- src/lib/form-validation/loans/lend.ts
- src/pages/Loans/LoansOverview/components/LoanModal/BorrowForm.tsx
- src/pages/Loans/LoansOverview/components/LoanModal/LendForm.tsx
- src/pages/Loans/LoansOverview/components/LoanModal/LoanModal.style.tsx
- src/pages/Loans/LoansOverview/components/LoanModal/LoanModal.tsx
- src/pages/Loans/LoansOverview/utils/use-loan-form-data.tsx
- src/utils/hooks/api/loans/get-usd-values.ts
- src/utils/hooks/api/loans/use-get-account-loans-overview.tsx
- added last Tabs feature
- clean up repeated code in Loans Form
> refactor(Loans): loans forms and modal

- src/common/utils/utils.ts
numbers with 6 digit get compacted
> feat: add compact formatUSD

- src/pages/Bridge/IssueForm/index.tsx
- src/pages/Bridge/RedeemForm/index.tsx
> refactor: move amount received closer to input on issue/redeem

- package.json
- src/components/IssueUI/IssueRequestStatusUI/ManualIssueExecutionUI/index.tsx
- src/pages/Bridge/BurnForm/index.tsx
- src/pages/Bridge/IssueForm/index.tsx
- src/pages/Loans/LoansOverview/utils/use-loan-form-data.tsx
- src/services/fetchers/cumulative-volumes-fetcher.ts
- src/services/fetchers/oracle-exchange-rates-fetcher.ts
- src/test/mocks/@interlay/interbtc-api/index.ts
- src/test/mocks/@interlay/interbtc-api/parachain/loans.ts
- src/utils/helpers/currencies.ts
- src/utils/hooks/api/use-get-collateral-currencies.tsx
- src/utils/hooks/api/use-get-currencies.tsx
- src/utils/hooks/api/use-get-prices.tsx
- yarn.lock
Updating UI with latest version of lib Interlend branch and fixing breaking changes caused by `Currency` refactorings. 
**Important note: Support for lend tokens being used as vault collateral is not added at this PR, and must be added later.**
> chore: update lib version and fix breaking changes

- package.json
- src/pages/Vaults/VaultsOverview/components/CreateVaultWizard/DespositCollateralStep.tsx
- src/pages/Vaults/VaultsOverview/components/VaultsTable/VaultsTable.tsx
- src/pages/Vaults/VaultsOverview/utils/use-deposit-collateral.tsx
- src/utils/hooks/api/vaults/use-get-available-vaults.tsx
- yarn.lock
Update lib and fix breaking changes
> Interlay Tom/hotfix/vault collateral lib update fixed

- src/assets/locales/en/translation.json
- src/pages/Bridge/RedeemForm/index.tsx
> chore: change redeem max capacity error message

- .env.dev
- src/components/Vaults/VaultsSelector/index.tsx
Add identities to vault selector. This is a quick fix - as little refactoring as possible as we'll be implementing an updated vault selector component in the near future.
> wip: get vault identity

- src/constants.ts
- src/parts/InterlayHelmet/index.tsx
> feature: add fathom script

- src/utils/hooks/api/use-get-currencies.tsx
Making lendToken fetching in currencies hook dependent on feature flag to ensure compatibility with mainnet.
> refactor: change currencies hook to fetch lend tokens based on feature flag

- .github/pull_request_template.md
Made a spelling mistake
Instances of the US spelling of behaviour
No instances of the US spelling of behaviour
Create a PR and check that behaviour is spelt correctly
> chore: fix spelling

- package.json
> chore: release v2.22.0

- src/pages/Loans/LoansOverview/hooks/use-get-ltv.tsx
- src/utils/hooks/api/loans/use-get-account-positions.tsx
Fixes a bad calculation
Breaks page when there is no supply (lending positions)
Handles when there is no supply
- Open lending page when there are no lending positions or no wallet connected.
> fix(Loans): Net APY

- src/lib/form-validation/loans/borrow.ts
Fix Max repay
No max amount when repaying
Added user balance  as max amount when repaying loan
- Open borrow position
- Try to repay with over borrowing amount.
> fix(Loans): max repay

- package.json
> chore: release v2.23.0

- src/App.tsx
- src/components/TestnetBanner/index.tsx
> Add a banner to inform users of potential testnet resets
n/a
n/a
Banner has been added to the layout component so should be shown on every page of the application
> feature: add testnet banner

- package.json
- src/assets/locales/en/translation.json
- src/pages/Transfer/CrossChainTransferForm/index.tsx
> Tom/release/kintsugi 2.24.1

- package.json
- src/assets/locales/en/translation.json
- src/pages/Transfer/CrossChainTransferForm/index.tsx
> Tom/release/interlay 2.24.1

- src/pages/Vaults/Vault/RequestReplacementModal/index.tsx
Hotfix related to: https://github.com/interlay/interbtc-ui/pull/772
> hotfix: kintsugi add check for required griefing collateral

- src/pages/Vaults/Vault/RequestReplacementModal/index.tsx
Hotfix related to: https://github.com/interlay/interbtc-ui/pull/772
> hotfix: interlay add check for required griefing collateral

- package.json
- src/component-library/Divider/Divider.stories.tsx
- src/component-library/Divider/Divider.style.tsx
- src/component-library/Divider/Divider.tsx
- src/component-library/Divider/index.tsx
- src/component-library/index.tsx
- src/component-library/utils/prop-types.ts
- yarn.lock
> feat(Divider): add component

- src/component-library/Modal/Modal.style.tsx
> fix(Modal): width

- src/component-library/Modal/Modal.style.tsx
- src/component-library/Modal/Modal.tsx
- src/component-library/theme/theme.base.css
- src/component-library/theme/theme.ts
- src/pages/Loans/LoansOverview/components/LoanModal/LoanModal.style.tsx
Was no able to click close btn on some edge cases
Btn is not reachable
Btn is reachable 
> Lending flow
> fix(Modal): close btn

- src/component-library/CTA/CTA.tsx
- src/pages/Vaults/VaultsOverview/components/CreateVaultWizard/DespositCollateralStep.tsx
- src/pages/Vaults/VaultsOverview/components/CreateVaultWizard/DisclaimerStep.tsx
Fixing regression from previous features.
One step of the vault onboarding was being ignored.
Onboarding flow works fine.
> Using an account that has a vault
1. Navigate to Vaults page
2. Add new vault
3. Complete the whole flow.
> fix: vault onboarding

- src/component-library/Accordion/Accordion.tsx
- src/component-library/Accordion/AccordionItem.tsx
Add the possibility to change accordion size, which affects the `h3` inside `AccordionItem`.
> feat(Accordion): add size prop

- src/pages/Vaults/Vault/components/InsightsList/InsightsList.tsx
- src/pages/Vaults/Vault/components/Rewards/Rewards.tsx
- src/pages/Vaults/Vault/components/TransactionHistory/TransactionHistory.tsx
- src/pages/Vaults/Vault/components/VaultCollateral/VaultCollateral.tsx
- src/pages/Vaults/Vault/components/VaultInfo/VaultInfo.tsx
Some types that will break whenever we add new props to Card component.
> chore(Vault): fix component types

- src/index.tsx
Issue: https://github.com/adobe/react-spectrum/issues/779#issuecomment-1353734729
Removing `strict mode` does not have an affect on production but solely on development enviorment.
> chore: remove strict mode

- src/component-library/TokenInput/TokenInput.tsx
balance is being hidden when it is 0
balance is being hidden when it is 0
balance is not hidden when it is 0
> fix(TokenInput): balance

- package.json
> Master version bump

- package.json
> Interlay version bump

- package.json
- yarn.lock
> fix: bump lib

- src/component-library/Input/Input.tsx
- src/component-library/NumberInput/NumberInput.tsx
- src/component-library/TokenInput/TokenInput.tsx
Some improvements to accessibility
> fix: TokenInput, NumberInput and Input aria

- src/component-library/CoinIcon/CoinIcon.tsx
- src/component-library/theme/theme.interlay.css
- src/component-library/theme/theme.kintsugi.css
- src/component-library/theme/theme.ts
Updating colors according to Jay feedback
> fix(CoinIcon): fallback icon colors

- package.json
> chore: update lib to 0.32.1

- yarn.lock
> fix: yarn references for lib 0.32.1

- src/pages/Loans/LoansOverview/components/ApyTooltip/AssetGroup.tsx
- src/pages/Loans/LoansOverview/components/ApyTooltip/RewardsGroup.tsx
- src/pages/Loans/LoansOverview/components/BorrowAssetsTable/BorrowAssetsTable.tsx
- src/pages/Loans/LoansOverview/components/LendAssetsTable/LendAssetsTable.tsx
- src/pages/Loans/LoansOverview/components/LoansBaseTable/BalanceCell.tsx
Failing to access usd value for some assets
Accessing prices in a unsafe way
Safely getting prices
Visit lending
> fix(Loans): get prices

- src/component-library/Select/Select.stories.tsx
- src/component-library/Select/Select.style.tsx
- src/component-library/Select/SelectTrigger.tsx
- src/component-library/Select/index.tsx
- src/component-library/theme/theme.interlay.css
- src/component-library/theme/theme.kintsugi.css
- src/component-library/theme/theme.ts
Just a button that looks like a select, which we hope to use when `Select` is added.
> feat(Select): add SelectTrigger

- src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx
- src/pages/AMM/Pools/components/PoolsTables/PoolsTable.tsx
- src/pages/AMM/Swap/components/SwapLiquidity/SwapLiquidity.tsx
- src/pages/AMM/shared/utils.ts
Fixing wrong liquidity calculations
Pool liquidity and account supplied liquidity were not correct.
Calculations are fixed
AMM
> fix: Pools and Swap liquidity calculations

- src/component-library/TokenInput/TokenSelect.tsx
[> Add a brief description
](https://www.notion.so/interlay/Disable-auto-fill-in-all-number-input-fields-2fcfa2a37ea04e9eae0ee8f3dd6b14d6)
Unwanted autofill symbol.
Remove unwanted autofill symbol
AMM
> fix(TokenInput): autoComplete off

- package.json
- src/pages/AMM/Swap/components/SwapInfo/SwapInfo.tsx
- yarn.lock
Update lib
Price impact was a string
Price impact is now Big
Swap
> feat: update lib and handle breaking changes

- src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx
- src/pages/AMM/Swap/components/SwapInfo/SwapInfo.tsx
- src/pages/AMM/Swap/hooks/use-swap-form-data.tsx
- src/pages/Loans/LoansOverview/components/CollateralModal/CollateralModal.tsx
Changes to Lending Collateral Modal and Swap page token modal.
Collateral modal not using ModalFooter.
Swap Token Select does not have the correct prices and formatting.
Cleaning Swap Input, does not affect Output.
Fixes all above
Lending and Swap
> fix: Lending collateral modal and swap modal formatting

- src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx
Loading indication was not being shown while user was changing input
Swap
> fix(Swap): loading trade indicator

- package.json
- yarn.lock
> chore: upgrade lib to 0.32.4

- package.json
- yarn.lock
Update lib to 0.32.7 - fix for slippage computation.
> chore: update lib 0.32.7

- package.json
- src/pages/AMM/Pools/components/PoolsTables/utils.ts
- yarn.lock
Updating lib to 0.32.8 - fix for incorrect APR computation - enables also farming reward claiming.
> chore: update to lib 0.32.8

- src/legacy-components/Tokens/TokenSelector/index.tsx
- src/legacy-components/Tokens/index.tsx
> feat: add all available currencies to top nav select

- src/config/links.ts
Update link to competition dashboard.
> chore: update competition dashboard link

- src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx
Was not showing rewards in dollars on the Pools page
> fix(Pools): format rewards USD

- src/pages/Loans/LoansOverview/hooks/use-get-ltv.tsx
There was a formatting being done on the ranges that could have made the NaN issue appear. The fix is to remove unnecessary formatting.
Loans: create collateral lend and borrow some asset
> fix(Loans): ranges percentage formatting

- src/pages/Loans/LoansOverview/components/ApyTooltip/AssetGroup.tsx
- src/pages/Loans/LoansOverview/components/LoansBaseTable/ApyCell.tsx
Improve formatting on borrow positions table
> fix(Loans): improve formatting borrow position table

- src/components/AccountSelect/AccountListModal.tsx
- src/pages/Transfer/CrossChainTransferForm/components/ChainSelect/ChainListModal.tsx
Remove padding from modal body for select components
> Modal padding

- src/legacy-components/TestnetBanner/index.tsx
> refactor: update testnet banner

- src/pages/Transfer/CrossChainTransferForm/CrossChainTransferForm.tsx
- src/utils/hooks/api/xcm/get-xcm-endpoints.ts
- src/utils/hooks/api/xcm/use-xcm-bridge.ts
> Refactor useXCMBridge hook

- src/legacy-components/TestnetBanner/index.tsx
> refactor: fix regression with testnet banner

- src/legacy-components/Tokens/index.tsx
- src/utils/helpers/coin-icon.ts
Added logic to display LpTokens in our `Tokens` component
> feat: apply CoinIcon for LpTokens

- src/utils/hooks/api/vaults/use-get-vault-data.tsx
Hotfix: filter out erroring vaults
> hotfix: filter erroring vaults

- README.md
- src/config/links.ts
Fix discord link for interlay branch.
> interlay/chore: change discord link

- README.md
- src/config/links.ts
Replacing old discord link with a valid new one.
> chore: change discord link

- src/assets/icons/InformationCircle.tsx
- src/assets/icons/index.ts
- src/legacy-components/tooltips/InformationTooltip/index.tsx
- src/pages/Loans/LoansOverview/components/LTVMeter.tsx/LTVLegend.tsx
- src/pages/Loans/LoansOverview/components/LTVMeter.tsx/LTVMeter.style.tsx
Some tests were getting polluted by logs from our tooltip. The problem is that the tooltip was not able to pass a ref.
> Lending
> Bridge
> fix: tooltip error

- src/component-library/TokenInput/TokenInput.stories.tsx
- src/component-library/TokenInput/TokenInput.tsx
- src/component-library/TokenInput/TokenSelect.tsx
- src/component-library/utils/input.ts
- src/pages/AMM/Pools/components/PoolsTables/PoolsTable.tsx
- src/pages/AMM/Swap/components/SwapForm/SwapDivider.tsx
- src/pages/AMM/shared/components/SlippageManager/SlippageManager.tsx
Some fixes to issues that were found while testing Pools and Swap page.
> fix: improve swap and pools accessibility

- package.json
- yarn.lock
> chore: bump bridge

- src/utils/hooks/use-wallet.ts
This hook aims to give a clear state of the user wallet. 
`accounts` are defined even when the user is disconnected
Handles state correctly for when the user is connect or disconnected.
> feat: add wallet hook

- src/assets/locales/en/translation.json
- src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx
- src/pages/Loans/LoansOverview/components/CollateralModal/CollateralModal.tsx
- src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx
- src/pages/Loans/LoansOverview/components/LoansInsights/LoansInsights.tsx
Some feedback messages were missing for pools and lending
> fix: add transaction feedback to pools and lending

- src/pages/Staking/index.tsx
Hotfix to remove banner from Kintsugi production app
> chore: remove block time banner

- src/pages/Staking/index.tsx
Remove warning banner—issue has been fixed
> chore: remove warning banner

- src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx
Fix regression introduced when resolving merge conflict
> fix: token input regression

- src/assets/locales/en/translation.json
> Add view_details dictionary item

- src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx
> fix(loans): fix max repay amount

- package.json
- src/index.tsx
- yarn.lock
> Configure Sentry

- package.json
- yarn.lock
Update of lib to fix loading of Vault Dashboard.
> chore: update lib with hotfix for Vault Dashboard

- src/pages/Loans/LoansOverview/components/LoanForm/LoanForm.tsx
Reverts interlay/interbtc-ui#1043
> Revert "fix(loans): fix max repay amount"

- src/pages/Loans/LoansOverview/utils/apy.ts
> fix(Loans): apy label

- src/legacy-components/Tokens/TokenSelector/index.tsx
- src/utils/hooks/api/tokens/use-get-balances.tsx
> fix: available balance to use transferable 

- src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx
- src/utils/hooks/api/tokens/use-get-balances.tsx
- adds missing refetch interval to `balances` hook
> feat: add refetch balances and form validation deps

- package.json
- yarn.lock
Master is failing to I have to revert resolutions.
> fix: package.json resolutions

- package.json
- src/assets/locales/en/translation.json
- src/legacy-components/Tokens/TokenSelector/index.tsx
- src/pages/Bridge/IssueForm/index.tsx
Hotfix for two balance issues:
* Top bar is showing incorrect balance when selected (correct balance shown in drop down)
* Issue form is validating against free balance rather than transferable balance
> Kintsugi: Tom/hotfix/issue validation

- src/test/pages/Issue.test.tsx
- yarn.lock
> chore: update yarn.lock and fix issue form snapshot test

- package.json
- src/utils/hooks/api/xcm/use-xcm-bridge.ts
- yarn.lock
Bump XCM bridge to latest version and fix breaking change
> chore: bump XCM bridge

- package.json
- src/utils/hooks/api/xcm/use-xcm-bridge.ts
- yarn.lock
Revert to patched version of bridge 0.2.x to fix regression on Kintsugi
> fix: revert to using 0.2.x version of the bridge

- src/pages/Transfer/CrossChainTransferForm/index.tsx
Hotfix: disable failing XCM channels
> hotifx: make kintsugi the only valid originating XCM chain

- src/assets/locales/en/translation.json
- src/pages/AMM/Swap/components/PriceImpactModal/PriceImpactModal.tsx
Price impact warning copy was ambiguous—this PR makes it clearer
> chore: improve price impact warning copy

- package.json
- src/pages/Transfer/CrossChainTransferForm/index.tsx
- yarn.lock
Bump bridge to re-enable Kusama/Statemine XCM
> Bump bridge and revert hotfix

- src/pages/AMM/Swap/Swap.tsx
- src/utils/hooks/api/use-get-currencies.tsx
- src/utils/hooks/use-query-params.ts
Fixing swap form from being automatically cleared. [Discord thread](https://discord.com/channels/745259537707040778/920489659790929960/1093136576449630339)
> fix(amm): use correct hooks dependencies

- src/utils/hooks/api/use-get-currencies.tsx
Fixing dependency arrays for other callbacks in useGetCurrencies hook.
> fix: update useGetCurrencies callbacks dependency arrays

- src/App.tsx
- src/pages/Wallet/WalletOverview/WalletOverview.tsx
- src/pages/Wallet/WalletOverview/components/WalletInsights/WalletInsights.tsx
- src/utils/hooks/api/amm/use-get-account-pools.tsx
Closes #1100 
Total wallet balance is calculated incorrectly
Total balance ignores borrow, lend, and liquidity pools
This PR implements the first solution described in the ticket:
* Takes the raw total balance
* Adds lend positions
* Subtracts borrow positions
* Adds liquidity positions
Check that the total wallet balance on the wallet page is as expected. (This can be verified manually using the total figures shown in the tables).
> [wallet] improve wallet balance

- package.json
- src/pages/Staking/index.tsx
> [release] Interlay 2.9.5

- src/pages/Staking/index.tsx
Revert last change to staking page
> fix: revert change which blocks rewards calculation

- package.json
- src/pages/Staking/index.tsx
> [release] Interlay 2.29.6

- package.json
- src/pages/Staking/index.tsx
> [release] Kintsugi 2.29.6

- src/parts/Topbar/index.tsx
> fix: use legacy governance token link on Interlay

- src/utils/hooks/use-sign-message.ts
Config—disable signing without needing to revert changes
> refactor: disable signature get request when no signer api

- src/test/pages/Pools.test.tsx
- src/utils/hooks/api/amm/use-get-account-pools.tsx
Fix `enabled` check on `useGetAccountPools`
> fix(Pools): get account liquidity hook

- src/pages/Bridge/IssueForm/index.tsx
- src/pages/Bridge/RedeemForm/index.tsx
- src/pages/Transfer/CrossChainTransferForm/index.tsx
- src/pages/Vaults/Vault/RequestIssueModal/index.tsx
- src/pages/Vaults/Vault/RequestRedeemModal/index.tsx
- src/pages/Vaults/Vault/RequestReplacementModal/index.tsx
- src/test/mocks/@interlay/interbtc-api/index.ts
- src/test/mocks/setup.tsx
- src/test/mocks/utils/helpers/extrinsic.ts
- src/test/mocks/utils/helpers/index.ts
- src/test/mocks/utils/index.ts
- src/utils/helpers/extrinsic.ts
Adding mocks for tests needed after updating to submittable extrinsic lib refactor. Adding method to construct `ExtrinsicStatus` with check that bridge has been initialized.
New mocks and function to construct `ExtrinsicStatus`.
> refactor: add bridge initializaiton check to extrinsic status builder and add mocks for tests

- src/components/PoolsTable/PoolsTable.tsx
Make 7 day volume available in both tables
Only show 7 day volume for available pools
Shows for both tables
- Pools Page
> fix(Pools): make 7 day volume available for my pools

- src/component-library/TokenInput/TokenInput.tsx
Ticker state was not currently handled. 0 balance was being shown for fields without label.
> fix(TokenInput): ticker state

- package.json
- src/component-library/TokenInput/TokenInput.tsx
- src/components/PoolsTable/PoolsTable.tsx
- src/pages/Staking/index.tsx
> [release] Kintsugi 2.30.2

- package.json
- src/component-library/TokenInput/TokenInput.tsx
- src/components/PoolsTable/PoolsTable.tsx
- src/pages/Staking/index.tsx
> [release] Interlay 2.30.2

- src/pages/Staking/index.tsx
> refactor: invalidate queries

- package.json
- src/config/relay-chains.tsx
- src/pages/Staking/index.tsx
> [release] Interlay 2.30.5

- api/market_data.py
> chore: update coingecko api endpoint

- src/components/IsAuthenticated/IsAuthenticated.tsx
- src/components/IsAuthenticated/index.tsx
- src/components/index.tsx
- src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx
- src/pages/Loans/LoansOverview/components/LoansInsights/LoansInsights.tsx
- src/pages/Vaults/Vault/components/Rewards/Rewards.tsx
Add `IsAuthenticated` and apply it to some missing transactions CTAs
> feat: add IsAuthenticated and apply to claim rewards

- src/utils/hooks/use-sign-message.ts
Fetch query was not being called on mount. Took a chance to improve a little bit the logic.
Fetch on signature was only occuring on wallet change
Done also on mount
> Refresh page on unsigned account and modal should not appear but button should be disabled on forms.
> Form buttons should be enabled on signed accounts on page mount
> fix: use-sign-message

- src/utils/hooks/use-sign-message.ts
> fix: sign message hook

- .eslintignore
- src/utils/hooks/api/loans/use-get-account-subsidy-rewards.tsx
Remove unused imports from subsidy rewards hook
> fix: remove unused imports

- src/components/FundWallet/FundWallet.tsx
- src/components/FundWallet/use-entities.tsx
- src/config/links.ts
- src/utils/constants/links.ts
Fix links to correctly redirect to external source
> fix: fund wallet links

- package.json
> chore: bump version number

- src/components/FundWallet/FundWallet.tsx
- src/parts/Topbar/GetGovernanceTokenUI/index.tsx
- src/test/pages/Wallet.test.tsx
Allow buy button on wallet page to open fund wallet modal
> fix(Wallet): buy button

- package.json
- src/components/FundWallet/FundWallet.tsx
- src/components/LoanPositionsTable/ApyCell.tsx
- src/components/LoanPositionsTable/LoanPositionsTable.tsx
- src/pages/Loans/LoansOverview/components/BorrowAssetsTable/BorrowAssetsTable.tsx
- src/pages/Loans/LoansOverview/components/LendAssetsTable/LendAssetsTable.tsx
- src/parts/Topbar/GetGovernanceTokenUI/index.tsx
- src/test/pages/Wallet.test.tsx
> [release] Kintsugi 2.31.2

- api/geoblock.js
- vercel.json
> api - geolocation endpoint

- src/utils/hooks/api/use-get-prices.tsx
> fix: put qtoken price fetching behind feature flag

- api/geoblock.js
- package.json
- src/utils/hooks/api/use-get-prices.tsx
- vercel.json
> [release] Interlay 2.31.3

- api/geoblock.js
- package.json
- src/utils/hooks/api/use-get-prices.tsx
- vercel.json
> [release] kintsugi 2.31.3

- src/components/Geoblock/Geoblock.tsx
- src/utils/hooks/use-feature-flag.ts
- src/utils/hooks/use-geoblocking.ts
> feature: add geoblock feature flag

- package.json
- yarn.lock
> [release] Kintsugi 2.32.5

- package.json
- yarn.lock
> [release] Interlay 2.32.5

- src/component-library/Dialog/Dialog.style.tsx
- src/component-library/Modal/Modal.style.tsx
- src/component-library/Popover/Popover.style.tsx
The latest update to Modal created problem with width
> fix: Dialog, Modal and Popover

- src/utils/hooks/use-countdown.ts
> chore: remove console.log

- src/utils/hooks/api/use-get-vesting-data.tsx
> fix: get vesting data

- src/utils/hooks/transaction/utils/submit.ts
> fix: transaction none

- package.json
- src/components/LoanApyTooltip/BreakdownGroup.tsx
- src/components/LoanApyTooltip/LoanApyTooltip.tsx
- src/components/LoanPositionsTable/ApyCell.tsx
- src/components/LoanPositionsTable/LoanPositionsTable.tsx
- src/pages/Loans/LoansOverview/components/BorrowAssetsTable/BorrowAssetsTable.tsx
- src/pages/Loans/LoansOverview/components/LendAssetsTable/LendAssetsTable.tsx
- src/pages/Loans/LoansOverview/components/LoanActionInfo/RewardsGroup.tsx
- src/utils/helpers/loans.ts
- src/utils/hooks/api/loans/use-get-account-lending-statistics.tsx
- yarn.lock
Found some improvements for useForm implementation
> fix: improve useForm

- src/components/TransactionFeeDetails/TransactionFeeDetails.tsx
- src/pages/Bridge/BridgeOverview/components/IssueForm/IssueForm.tsx
- src/pages/Bridge/BridgeOverview/components/TransactionDetails/TransactionDetails.tsx
- src/pages/Transfer/TransferForms/components/TransferForm/TransferForm.tsx
- src/utils/hooks/transaction/use-transaction.ts
> feat: integrate use-transaction with TransactionFeeDetails

- api/market_data.py
> api: use diadata as main datasource

- src/utils/hooks/api/xcm/xcm-endpoints.ts
> chore: update XCM RPCs

- package.json
- src/utils/hooks/api/xcm/xcm-endpoints.ts
> [release] Kintsugi 2.34.1

- package.json
- src/utils/hooks/api/xcm/xcm-endpoints.ts
> [release] Interlay 2.34.1

- api/market_data.py
> api: switch to coingecko pro url

- src/utils/hooks/use-select-currency.tsx
Adding sorting of currencies by account's balance.
> feat: sort currencies by balance

- src/assets/locales/en/translation.json
> chore: update price impact warning copy

- src/component-library/CTA/CTA.style.tsx
- src/component-library/CTA/CTA.tsx
- src/component-library/theme/theme.interlay.css
Forced load spinner to have CTA text color
> feat: change LoadingSpinner styles and CTA loading spinner

- src/assets/locales/en/translation.json
- src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/AvailableAssetsTable.tsx
- src/utils/constants/currency.ts
Add USDT to available assets and change switch label
> feat(Wallet): add USDT and change switch label

- src/component-library/TokenInput/TokenListItem.tsx
- src/components/TransactionDetails/TransactionSelectToken.tsx
> fix: select token modal list style

- src/assets/locales/en/translation.json
- src/components/TransactionFeeDetails/TransactionFeeDetails.tsx
- src/pages/Bridge/BridgeOverview/components/IssueForm/IssueForm.tsx
- src/pages/Bridge/BridgeOverview/components/TransactionDetails/TransactionDetails.tsx
The problem was that `GOVERNANCE` is the default currency and when applying styles on select currency, we were not checking if that selected currency was disabled. Also fixed a shift in the issue UI.
> fix: improve IssueForm insufficient funds notice

- src/utils/hooks/api/xcm/use-xcm-bridge.ts
This is not a complete fix for the performance issues, but works as an interim fix
> fix: disable fetch on focus

- src/utils/hooks/api/amm/use-get-account-pools.tsx
@peterslany this fixes a typo I found while I was looking at the pools UI code. Very low priority so I'll leave it with you to merge in whenever convenient.
> Typo in pools function

- package.json
- yarn.lock
> [hotfix]: Kintsugi 2.34.2

- src/pages/Onboarding/Onboarding.tsx
- src/utils/hooks/use-select-currency.tsx
- removing onboarding link for faucet
- fix select fee list
> fix: onboarding and empty fee selector

- api/market_data.py
Adds additional asset IDs and their Dia endpoints
> api: add dia asset ids to market data endpoint

- src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/AvailableAssetsTable.tsx
- src/pages/Wallet/WalletOverview/components/WelcomeBanner/WelcomeBanner.tsx
Add missing links to wallet page
> fix(Wallet): add missing guide link

- src/pages/AMM/Pools/components/DepositForm/DepositForm.tsx
> fix(Pools): deposit validation

- src/component-library/Modal/ModalWrapper.tsx
- src/lib/form/use-form.tsx
- src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx
- src/pages/AMM/Swap/components/SwapForm/SwapForm.tsx
- src/pages/Bridge/BridgeOverview/components/IssueForm/IssueForm.tsx
- src/pages/Bridge/BridgeOverview/components/RedeemForm/RedeemForm.tsx
- src/pages/Transfer/TransferForms/components/CrossChainTransferForm/CrossChainTransferForm.tsx
- src/pages/Transfer/TransferForms/components/TransferForm/TransferForm.tsx
- src/utils/hooks/api/oracle/use-get-oracle-currencies.ts
- src/utils/hooks/api/use-get-dex-volume.tsx
- src/utils/hooks/use-select-currency.tsx
With the latest tests fix I was able to catch some problems with our current code:
- `onSelectionChange` was being passed to components that do not handle this event.
- `useSelectCurrency` was running an oracle call when it was not necessary
- An import of Underlay was creating problems on our test env
-
> fix: various issues picked up from testing

- src/pages/AMM/Pools/components/PoolsInsights/PoolsInsights.tsx
- src/pages/Loans/LoansOverview/components/CollateralModal/CollateralModal.tsx
- src/pages/Loans/LoansOverview/components/LoansInsights/LoansInsights.tsx
The scenarios covered in the PR were prefetching fees while the modal was not open. This is unwanted.
> fix: prefetching fee scenarios

- src/pages/Wallet/WalletOverview/components/WelcomeBanner/WelcomeBanner.tsx
Hide onboarding button when feature is disabled
> fix: hide onboarding button

- src/utils/hooks/transaction/utils/fee.ts
> BYOF hotfix

- .storybook/preview.js
- src/component-library/WalletIcon/icons/ParitySignerCompanion.tsx
Fix Storybook error by correct display name syntax. This also disables the unused parts of the Chromatic workflow.
> Fix Storybook

- src/utils/hooks/api/bridge/use-get-redeem-data.tsx
Redeem is breaking on testnet because there is not capacity for redeem
> fix(Redeem): redeem limit when there is not capacity

- src/utils/hooks/api/bridge/use-get-redeem-data.tsx
My last PR related to redeem affected premium redeem
> fix(Redeem): premium redeem

- src/pages/BTC/BTCOverview/BTCOverview.tsx
- src/pages/BTC/BTCOverview/components/IssueForm/IssueForm.tsx
- src/pages/BTC/BTCOverview/components/RedeemForm/RedeemForm.tsx
- src/pages/SendAndReceive/SendAndReceiveForms/SendAndReceiveForms.tsx
- src/pages/SendAndReceive/SendAndReceiveForms/components/BridgeForm/BridgeForm.tsx
- src/pages/SendAndReceive/SendAndReceiveForms/components/TransferForm/TransferForm.tsx
- src/pages/Swap/Swap.tsx
- src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/ActionsCell.tsx
- src/types/bridge.ts
- src/utils/constants/links.ts
- src/utils/constants/tab-ids.ts
- src/utils/hooks/api/bridge/use-get-vaults.tsx
- src/utils/hooks/use-page-query-params.tsx
Add `ticker` and `xcmTicker` params
> feat(Transfer): add query params handling

- src/components/AuthModal/AuthModal.test.tsx
- src/utils/constants/wallets.ts
> Update number of wallets in test

- src/utils/hooks/transaction/utils/params.ts
This aims to fix an issue specially on swap page where you would try to test it with an amount that you do not own and also with amounts that are lower than the transaction fee.
https://discord.com/channels/745259537707040778/991617172407337030/1131215790029426790
> fix: fee affecting action amount calculation

- package.json
- src/utils/hooks/transaction/utils/params.ts
> [Release] Interlay 2.36.1

- package.json
- src/utils/hooks/transaction/utils/params.ts
> [Release] Kintsugi 2.36.1

- src/assets/locales/en/translation.json
- src/components/LoanPositionsTable/LoanPositionsTable.tsx
- src/pages/Loans/LoansOverview/components/BorrowAssetsTable/BorrowAssetsTable.tsx
- src/pages/Loans/LoansOverview/components/LendAssetsTable/LendAssetsTable.tsx
- src/pages/Wallet/WalletOverview/components/AvailableAssetsTable/AvailableAssetsTable.tsx
- src/pages/Wallet/WalletOverview/components/StakingTable/StakingTable.tsx
- src/pages/Wallet/WalletOverview/components/WelcomeBanner/WelcomeBanner.tsx
- src/parts/Sidebar/SidebarContent/Navigation/index.tsx
> chore: improve translactions

- src/App.tsx
- src/common/actions/general.actions.ts
- src/common/types/actions.types.ts
- src/legacy-components/Topbar/index.tsx
- src/store.ts
- src/utils/hooks/use-faucet.ts
> refactor: replace old faucet approach with use-faucet

- src/config/links.ts
- src/pages/Strategies/Strategies.tsx
- src/pages/Strategies/Strategy/Strategy.styles.tsx
- src/pages/Strategies/Strategy/Strategy.tsx
- src/pages/Strategies/components/StrategyInsights/StrategyInsights.styles.tsx
- src/pages/Strategies/components/StrategyInsights/StrategyInsights.tsx
> fix(Strategies): strategy page responsiveness

- src/hooks/use-feature-flag.ts
> fix: correct feature flag name

- .github/ISSUE_TEMPLATE/roadmap.md
- Adds a new issue template for roadmap items
None
None
None
> docs: roadmap item

- .github/workflows/projects.yml
- Updates the project automation
> feat: add roadmap items to roadmap but not backlog

- src/hooks/transaction/hooks/use-transaction.ts
- src/hooks/transaction/submission/submit.ts
Remove dry-run from XCM transfer transaction
> fix(SendAndReceive): remove dry-run from xcm

- src/hooks/transaction/hooks/use-transaction.ts
- src/hooks/transaction/submission/submit.ts
- src/pages/Pools/components/DepositForm/DepositForm.tsx
- src/test/pages/Pools.test.tsx
Fixes unwanted `dry-run` and custom ratio on pools deposit
> [hotfix] Kintsugi 2.38.0

- src/hooks/api/xcm/xcm-endpoints.ts
> [xcm] remove Karura dwellir node

- src/hooks/api/use-get-prices.tsx
> chore: remove console log

- src/legacy-components/IssueUI/index.tsx
> apply hotfix patch

- src/legacy-components/IssueUI/index.tsx
> issue hotfix patch

- src/component-library/WalletIcon/icons/SubWallet.tsx
> feat: update subwallet logo

- src/pages/BTC/BTCOverview/components/RedeemForm/RedeemForm.tsx
> fix(Redeem): show premium redeem compensation

- src/pages/BTC/BTCOverview/components/RedeemForm/RedeemForm.tsx
> Hotfix/kintsugi 2.39.1

- src/pages/Loans/LoansOverview/components/CollateralModal/CollateralForm.tsx
- src/pages/Loans/LoansOverview/components/CollateralModal/CollateralModal.tsx
> fix(Loans): collateral overlapping modal ref issue

- src/pages/Staking/components/StakingAccountDetails/StakingAccountDetails.tsx
- src/pages/Staking/components/StakingWithdrawCard/StakingWithdrawCard.tsx
> fix(Staking): close modal on submit

- package.json
- src/pages/Staking/components/StakingAccountDetails/StakingAccountDetails.tsx
- src/pages/Staking/components/StakingWithdrawCard/StakingWithdrawCard.tsx
- src/utils/constants/currency.ts
- yarn.lock
> [release] Kintsugi 2.40.1

- package.json
- src/pages/Staking/components/StakingAccountDetails/StakingAccountDetails.tsx
- src/pages/Staking/components/StakingWithdrawCard/StakingWithdrawCard.tsx
- src/utils/constants/currency.ts
- yarn.lock
> [release] Interlay 2.40.1

- api/currency-utils.js
- api/package-lock.json
- api/package.json
- api/tvl_dex.js
- api/tvl_loans.js
- package.json
- src/hooks/api/bridge/use-get-issue-request-limits.tsx
- src/pages/BTC/BTCOverview/components/IssueForm/IssueForm.tsx
- src/pages/Dashboard/cards/CollateralizationCard/index.tsx
- src/services/fetchers/oracle-exchange-rates-fetcher.ts
- vercel.json
- yarn.lock
> [release] Interlay 2.41.0

- src/config/relay-chains.tsx
- src/hooks/api/xcm/xcm-endpoints.ts
Hotfix to use dwellir node for Parallel XCM channel.
> fix: switch Parallel RCP node

- package.json
- src/hooks/api/xcm/xcm-endpoints.ts
> [release] Kintsugi 2.41.1

- package.json
- src/hooks/api/xcm/xcm-endpoints.ts
> [release] Interlay 2.41.1

- api/market_data.js
- package.json
> [release] Kintsugi 2.41.2

- api/market_data.js
- package.json
> [release] Interlay 2.41.2

- package.json
- yarn.lock
> [release] Kintsugi 2.41.5

- package.json
- src/config/charts.ts
- src/pages/Dashboard/LineChart/index.tsx
> [release] Kintsugi 2.41.6

- package.json
- src/config/charts.ts
- src/pages/Dashboard/LineChart/index.tsx
> [release] Interlay 2.41.6

- package.json
- src/config/charts.ts
- src/pages/Dashboard/IssuedChart/index.tsx
- src/pages/Dashboard/cards/ActiveVaultsCard/index.tsx
- src/pages/Dashboard/sub-pages/Home/LockedCollateralsCard/index.tsx
- src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/RedeemedChart/index.tsx
- src/pages/Dashboard/sub-pages/Vaults/LockedCollateralCard/index.tsx
> [release] Kintsugi 2.41.7

- package.json
- src/config/charts.ts
- src/pages/Dashboard/IssuedChart/index.tsx
- src/pages/Dashboard/cards/ActiveVaultsCard/index.tsx
- src/pages/Dashboard/sub-pages/Home/LockedCollateralsCard/index.tsx
- src/pages/Dashboard/sub-pages/RedeemRequests/UpperContent/RedeemedChart/index.tsx
- src/pages/Dashboard/sub-pages/Vaults/LockedCollateralCard/index.tsx
> [release] Interlay 2.41.7

- package.json
- src/pages/SendAndReceive/SendAndReceiveForms/components/BridgeForm/BridgeForm.tsx
> [release] Interlay 2.41.8

- package.json
- yarn.lock
> [release] Interlay 2.41.9

- package.json
- src/pages/SendAndReceive/SendAndReceiveForms/components/BridgeForm/BridgeForm.tsx
- yarn.lock
> [release] Kintsugi 2.41.10

- package.json
- src/pages/SendAndReceive/SendAndReceiveForms/components/BridgeForm/BridgeForm.tsx
- yarn.lock
> [release] Interlay 2.41.10

- src/hooks/api/xcm/xcm-endpoints.ts
Replace wss endpoints for:
- Polkadot
- Kusama
- AssetHub for both above
> chore: Update xcm-endpoints.ts

- package.json
- src/hooks/api/xcm/xcm-endpoints.ts
- yarn.lock
and add wss endpoints for Phala, and a few more for Bifrost Polkadot.
> Feat: bump xcm lib

- package.json
- src/App.tsx
- src/components/Layout/Layout.tsx
- src/lib/form/schemas/bob.ts
- src/lib/form/schemas/index.ts
- src/lib/form/validate.ts
- src/lib/form/yup.custom.ts
- src/pages/BOB/BOB.styles.tsx
- src/pages/BOB/BOB.tsx
- src/pages/BOB/index.tsx
- src/utils/constants/links.ts
- yarn.lock
> feature: bob x interlay

- package.json
- src/App.tsx
- src/components/AppAlert/AppAlert.styles.tsx
- src/components/AppAlert/AppAlert.tsx
- src/components/AppAlert/index.tsx
- src/components/Layout/Layout.tsx
- src/hooks/use-local-storage.ts
- src/lib/form/schemas/bob.ts
- src/lib/form/schemas/index.ts
- src/lib/form/validate.ts
- src/lib/form/yup.custom.ts
- src/pages/BOB/BOB.styles.tsx
- src/pages/BOB/BOB.tsx
- src/pages/BOB/index.tsx
- src/utils/constants/links.ts
- yarn.lock
> [release] interlay/2.41.16

- src/App.tsx
- src/hooks/use-feature-flag.ts
- src/pages/BOB/BOB.tsx
> [release] Kintsugi 2.41.17
